### ISSUE TITLE
unhandled exception on pub invite failure

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/patchwork#104]
how to reproduce: attempt to use invite code for pub server that is offline.

```
userFriendlyInviteError is not defined

ReferenceError: userFriendlyInviteError is not defined
    at addMeNext (/home/dinosaur/repos/ssbc/patchwork/ui/lib/ui/modals.js:123:27)
    at Object._requests.(anonymous function) (/home/dinosaur/repos/ssbc/patchwork/node_modules/packet-stream/index.js:37:5)
    at PacketStream._onrequest (/home/dinosaur/repos/ssbc/patchwork/node_modules/packet-stream/index.js:139:26)
    at PacketStream.write (/home/dinosaur/repos/ssbc/patchwork/node_modules/packet-stream/index.js:122:41)
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/muxrpc/pull-weird.js:56:15
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/pull-stream/throughs.js:97:9
    at EventEmitter.onincoming (/home/dinosaur/repos/ssbc/patchwork/node_modules/pull-ipc/index.js:54:7)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)

This was an unhandled exception.
```

**Comment by pfraze** [comment]
@ahdinosaur what version of patchwork are you using? This should be fixed in the current dev branch

**Comment by ahdinosaur** [comment]
ah oops, forgot i'm still on 4fb5789b5002bd587a273ef0a33bc2072b34baab, closing.
