### ISSUE TITLE
error when posting reply

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#106]
I got this error when trying to reply to a message on a flagged thread.
I had to restart patchwork after this, otherwise all the feeds are empty....

this one: %j/U0NvzBF5zwUcQ8U/AohHAmnfuR+xD7/JmL6B8YmuQ=.sha256

It actually posted my message though! (%z+2w2ECKVSCzcl2DpW+lNwMroLBc7Ez1w9F6pcrcjdQ=.sha256)

``` 
Cannot read property 'key' of null

TypeError: Cannot read property 'key' of null
    at /home/dominic/c/ssb/patchwork/ui/com/msg-thread.jsx:124:76
    at /home/dominic/c/ssb/patchwork/node_modules/pull-stream/sinks.js:15:33
    at /home/dominic/c/ssb/patchwork/node_modules/patchwork-threads/index.js:152:25
    at /home/dominic/c/ssb/patchwork/node_modules/multicb/index.js:17:16
    at Object.exports.getPostSummary.exports.iterateThreadAsync (/home/dominic/c/ssb/patchwork/node_modules/patchwork-threads/index.js:152:3)
    at Object.exports.getPostSummary.exports.decryptThread (/home/dominic/c/ssb/patchwork/node_modules/patchwork-threads/index.js:243:11)
    at /home/dominic/c/ssb/patchwork/ui/com/msg-thread.jsx:119:48
    at /home/dominic/c/ssb/patchwork/node_modules/pull-stream/throughs.js:33:7
    at /home/dominic/c/ssb/patchwork/node_modules/pull-stream/throughs.js:97:9
    at PacketStreamSubstream.weird.read (/home/dominic/c/ssb/patchwork/node_modules/muxrpc/pull-weird.js:33:7)
```
This was an unhandled exception.

**Comment by pfraze** [comment]
Will investigate. What version are you using? (commit sha)

**Comment by dominictarr** [comment]
e1692d8e2df921619d533214e6ab8ba132f94562

**Comment by pfraze** [comment]
Added some code to guard against this https://github.com/ssbc/patchwork/commit/6e481522cc51e7ada65331a0c35644cc28bc7bc2
