### ISSUE TITLE
Patchwork won't launch after update to Patchbay 8.0.1 

### ISSUE THREAD

**Issue by georgeowell** [ssbc/patchwork#1071]
Operating system: Ubuntu 18.04 (GNOME 3)

I am cross posting this issue from here as it does affect Patchwork: https://github.com/ssbc/patchbay/issues/344

After updating Patchbay to  patchbay-Linux-8.0.1-x86_64 via AppImage, Patchwork (Patchwork-3.11.6-linux-x86_64) fails to launch with the following error: 

```
'/home/user/Downloads/ssb-patchwork-3.12.0-x86_64.AppImage' 
SyntaxError: Unexpected string in JSON at position 38
    at JSON.parse (<anonymous>)
    at exports.parse (/tmp/.mount_ssb-paXyaKhW/resources/app.asar/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/tmp/.mount_ssb-paXyaKhW/resources/app.asar/node_modules/rc/index.js:30:20)
    at Array.forEach (<anonymous>)
    at module.exports (/tmp/.mount_ssb-paXyaKhW/resources/app.asar/node_modules/rc/index.js:43:36)
    at module.exports (/tmp/.mount_ssb-paXyaKhW/resources/app.asar/node_modules/ssb-config/inject.js:6:12)
    at setupContext (/tmp/.mount_ssb-paXyaKhW/resources/app.asar/index.js:170:43)
    at App.electron.app.on (/tmp/.mount_ssb-paXyaKhW/resources/app.asar/index.js:52:3)
    at App.emit (events.js:187:15)
```

**Comment by cryptix** [comment]
hmm.. that's not good. Can you check the contents of `.ssb/config`? that's the only JSON file involved in the loading process.

I fear the new config editor in patchbay might have messed with it's structure? 😰 

You can use `jq . $HOME/.ssb/config` to validate it's contents on the console and it should also give you a line number where it's wrong (not just char count (position) from beginning of the file)

**Comment by georgeowell** [comment]
@cryptix check the other issue: https://github.com/ssbc/patchbay/issues/344 

I have found this to be the case! It's the new `friendPub` option in Patchbay that mangled my `.ssb/config` JSON.

**Comment by christianbundy** [comment]
Could you `mv ~/.ssb/config ~/.ssb/config.bak` and try restarting? Sorry that your config got mangled, that's a bummer.
