### ISSUE TITLE
Unable to build from source on Ubuntu, spellchecking dependency?

### ISSUE THREAD

**Issue by skyebend** [ssbc/patchwork#1114]
After seeing notifications about the new release, I updated master branch and ran `npm install`

```
...
679 warn optional Skipping failed optional dependency /chokidar/fsevents:
680 warn notsup Not compatible with your operating system or architecture: fsevents@1.2.9
681 warn optional Skipping failed optional dependency /ssb-server/chokidar/fsevents:
682 warn notsup Not compatible with your operating system or architecture: fsevents@1.2.9
683 verbose stack Error: @felixrieseberg/spellchecker@4.0.10 install: `node-gyp rebuild`
683 verbose stack Exit status 1
683 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
683 verbose stack     at emitTwo (events.js:126:13)
683 verbose stack     at EventEmitter.emit (events.js:214:7)
683 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
683 verbose stack     at emitTwo (events.js:126:13)
683 verbose stack     at ChildProcess.emit (events.js:214:7)
683 verbose stack     at maybeClose (internal/child_process.js:925:16)
683 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
684 verbose pkgid @felixrieseberg/spellchecker@4.0.10
685 verbose cwd /home/skyebend/patchwork
686 error Linux 4.18.0-21-generic
687 error argv "/usr/bin/node" "/usr/bin/npm" "install"
688 error node v8.10.0
689 error npm  v3.5.2
690 error code ELIFECYCLE
691 error @felixrieseberg/spellchecker@4.0.10 install: `node-gyp rebuild`
691 error Exit status 1
692 error Failed at the @felixrieseberg/spellchecker@4.0.10 install script 'node-gyp rebuild'.
...
```

seems like it might be related to https://github.com/electron-userland/electron-spellchecker/issues/147

**Comment by christianbundy** [comment]
That's not good at all, sorry to hear you're bumping into this. I think @ahdinosaur mentioned that he had to upgrade to Node 10 to get it working, could you try that? I know it isn't a great solution, but I'm hoping it's a successful workaround.

**Comment by skyebend** [comment]
Thanks! was able to update to Node 10 (should mark as dependency?) but got npm audit security warnings. Was able to install with `npm install --no-audit`, but perhaps requirements of other packages need updates?
``` 
───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.3.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ ssb-db                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ ssb-db > mdmanifest > remark > chokidar > anymatch >         │
│               │ micromatch > braces                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/786                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.3.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ ssb-gossip                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ ssb-gossip > mdmanifest > remark > chokidar > anymatch >     │
│               │ micromatch > braces                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/786                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.3.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ ssb-invite                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ ssb-invite > mdmanifest > remark > chokidar > anymatch >     │
│               │ micromatch > braces                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/786                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Memory Exposure                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ bl                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.9.5 <1.0.0 || >=1.0.1                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ ssb-invite                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ ssb-invite > level-sublevel > levelup > bl                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/596                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 4 vulnerabilities (3 low, 1 moderate) in 11802 scanned packages
  4 vulnerabilities require manual review. See the full report for details.
```

**Comment by pospi** [comment]
FWIW building this same package crashes with Nodejs 10.x as of patchwork `v3.14.1` (probably slightly earlier), it seems like Nodejs 11.x is now a requirement.

**Comment by christianbundy** [comment]
@pospi 

Hmm, our build server uses Node 10 and that's what I use locally. If you're having a built error on Node 10 could you create a new issue? Would love to help debug! :sparkles:

**Comment by pospi** [comment]
Actually I think it's fine. Crash on `10.9.0` but builds OK on `10.16.0`, which is the latest LTS release.

**Comment by christianbundy** [comment]
Crap, thanks for letting me know. I hadn't heard of that yet but you just saved me a few hours of debugging for when someone inevitably runs into the problem on < 10.16. Thanks!
