### ISSUE TITLE
UsageError: Param 0 must have a .id of type "feedId"

### ISSUE THREAD

**Issue by dangerousbeans** [ssbc/patchwork#1136]
In 819ec20a81acca9c4af64c2de39862bfa35806d3 I am getting:

```sh
UsageError: Param 0 must have a .id of type "feedId"
    at new ZE (/home/joran/development/patchwork/node_modules/zerr/index.js:11:42)
    at ZError (/home/joran/development/patchwork/node_modules/zerr/index.js:13:14)
    at Object.createUserStreamOpts (/home/joran/development/patchwork/node_modules/ssb-db/lib/validators.js:146:14)
    at validate (/home/joran/development/patchwork/node_modules/muxrpc-validation/index.js:153:15)
    at Object.<anonymous> (/home/joran/development/patchwork/node_modules/muxrpc-validation/index.js:95:17)
    at Object.hooked (/home/joran/development/patchwork/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/joran/development/patchwork/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/home/joran/development/patchwork/node_modules/muxrpc/local-api.js:37:22)
    at PacketStreamSubstream.stream.read (/home/joran/development/patchwork/node_modules/muxrpc/stream.js:69:23)
    at PacketStream._onstream (/home/joran/development/patchwork/node_modules/packet-stream/index.js:228:11)
```

**Comment by christianbundy** [comment]
Where are you gettig this error? Do you know what's triggering it?

**Comment by dangerousbeans** [comment]
On patchwork launch, after some seconds, not sure what's triggering it yet.
It appears in the electron browser also

**Comment by christianbundy** [comment]
Does it happen only in Patchwork, or do you get the same thing with the latest ssb-server?

**Comment by dangerousbeans** [comment]
Just patchwork - ssb-server 15.0.2 seems okay

**Comment by dangerousbeans** [comment]
running with node v10.15.3

**Comment by dangerousbeans** [comment]
Here's a full startup log

```sh
joran@joran-UX305LA [08:35:44] [~/development/patchwork] [master *]
-> % npm run start

> ssb-patchwork@3.14.1 start /home/joran/development/patchwork
> electron index.js

{ path: '/home/joran/.ssb',
  party: true,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  gossip: { connections: 3, autoPopulate: false },
  connections:
   { outgoing: { net: [ { transform: 'shs' } ] },
     incoming:
      { net:
         [ { host: '127.0.0.1',
             port: 8008,
             scope: [ 'device' ],
             transform: 'shs' },
           { host: '::1', port: 8008, scope: [ 'device' ], transform: 'shs'
},
           { host: '192.168.0.109',
             port: 8008,
             scope: [ 'device', 'local', 'public' ],
             transform: 'shs' } ],
        ws:
         [ { host: '127.0.0.1',
             port: 8989,
             scope: [ 'device' ],
             transform: 'shs' },
           { host: '::1', port: 8989, scope: [ 'device' ], transform: 'shs'
},
           { host: '192.168.0.109',
             port: 8989,
             scope: [ 'device', 'local', 'public' ],
             transform: 'shs' } ],
        unix: [ { scope: 'device', transform: 'noauth' } ] } },
  timers:
   { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps:
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  port: 8008,
  blobsPort: 8989,
  server: true,
  plugins:
   { 'ssb-identities': true, 'ssb-names': true, 'ssb-clingy': true },
  _: [],
  configs: [ '/home/joran/.ssb/config' ],
  config: '/home/joran/.ssb/config',
  host: '192.168.0.109',
  ws:
   { host: '192.168.0.109',
     port: 8989,
     scope: [ 'device', 'local', 'public' ],
     transform: 'shs' },
  keys:
   { curve: 'ed25519',
     public: 'TXKFQehlyoSn8UJAIVP/k2BjFINC591MlBC2e2d24mA=.ed25519',
     private: null,
     id: '@TXKFQehlyoSn8UJAIVP/k2BjFINC591MlBC2e2d24mA=.ed25519' },
  remote:

 'unix:/home/joran/.ssb/socket:~noauth:TXKFQehlyoSn8UJAIVP/k2BjFINC591MlBC2e2d24mA='
}
Listening on http://localhost:7718/
[]
UsageError: Param 0 must have a .id of type "feedId"
    at new ZE
(/home/joran/development/patchwork/node_modules/zerr/index.js:11:42)
    at ZError
(/home/joran/development/patchwork/node_modules/zerr/index.js:13:14)
    at Object.createUserStreamOpts
(/home/joran/development/patchwork/node_modules/ssb-db/lib/validators.js:146:14)
    at validate
(/home/joran/development/patchwork/node_modules/muxrpc-validation/index.js:153:15)
    at Object.<anonymous>
(/home/joran/development/patchwork/node_modules/muxrpc-validation/index.js:95:17)
    at Object.hooked
(/home/joran/development/patchwork/node_modules/hoox/index.js:10:15)
    at Object.localCall
(/home/joran/development/patchwork/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous>
(/home/joran/development/patchwork/node_modules/muxrpc/local-api.js:37:22)
    at PacketStreamSubstream.stream.read
(/home/joran/development/patchwork/node_modules/muxrpc/stream.js:69:23)
    at PacketStream._onstream
(/home/joran/development/patchwork/node_modules/packet-stream/index.js:228:11)
```

**Comment by dangerousbeans** [comment]
Here's a full startup log

```sh
joran@joran-UX305LA [08:35:44] [~/development/patchwork] [master *]
-> % npm run start

> ssb-patchwork@3.14.1 start /home/joran/development/patchwork
> electron index.js

{ path: '/home/joran/.ssb',
  party: true,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  gossip: { connections: 3, autoPopulate: false },
  connections:
   { outgoing: { net: [ { transform: 'shs' } ] },
     incoming:
      { net:
         [ { host: '127.0.0.1',
             port: 8008,
             scope: [ 'device' ],
             transform: 'shs' },
           { host: '::1', port: 8008, scope: [ 'device' ], transform: 'shs' },
           { host: '192.168.0.109',
             port: 8008,
             scope: [ 'device', 'local', 'public' ],
             transform: 'shs' } ],
        ws:
         [ { host: '127.0.0.1',
             port: 8989,
             scope: [ 'device' ],
             transform: 'shs' },
           { host: '::1', port: 8989, scope: [ 'device' ], transform: 'shs' },
           { host: '192.168.0.109',
             port: 8989,
             scope: [ 'device', 'local', 'public' ],
             transform: 'shs' } ],
        unix: [ { scope: 'device', transform: 'noauth' } ] } },
  timers:
   { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps:
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  port: 8008,
  blobsPort: 8989,
  server: true,
  plugins:
   { 'ssb-identities': true, 'ssb-names': true, 'ssb-clingy': true },
  _: [],
  configs: [ '/home/joran/.ssb/config' ],
  config: '/home/joran/.ssb/config',
  host: '192.168.0.109',
  ws:
   { host: '192.168.0.109',
     port: 8989,
     scope: [ 'device', 'local', 'public' ],
     transform: 'shs' },
  keys:
   { curve: 'ed25519',
     public: 'TXKFQehlyoSn8UJAIVP/k2BjFINC591MlBC2e2d24mA=.ed25519',
     private: null,
     id: '@TXKFQehlyoSn8UJAIVP/k2BjFINC591MlBC2e2d24mA=.ed25519' },
  remote:
   'unix:/home/joran/.ssb/socket:~noauth:TXKFQehlyoSn8UJAIVP/k2BjFINC591MlBC2e2d24mA=' }
Listening on http://localhost:7718/
[]
UsageError: Param 0 must have a .id of type "feedId"
    at new ZE (/home/joran/development/patchwork/node_modules/zerr/index.js:11:42)
    at ZError (/home/joran/development/patchwork/node_modules/zerr/index.js:13:14)
    at Object.createUserStreamOpts (/home/joran/development/patchwork/node_modules/ssb-db/lib/validators.js:146:14)
    at validate (/home/joran/development/patchwork/node_modules/muxrpc-validation/index.js:153:15)
    at Object.<anonymous> (/home/joran/development/patchwork/node_modules/muxrpc-validation/index.js:95:17)
    at Object.hooked (/home/joran/development/patchwork/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/joran/development/patchwork/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/home/joran/development/patchwork/node_modules/muxrpc/local-api.js:37:22)
    at PacketStreamSubstream.stream.read (/home/joran/development/patchwork/node_modules/muxrpc/stream.js:69:23)
    at PacketStream._onstream (/home/joran/development/patchwork/node_modules/packet-stream/index.js:228:11)
```

**Comment by christianbundy** [comment]
Does Patchwork crash?

If not, could you try changing [this line](https://github.com/ssbc/patchwork/blob/1819a269eefb4a145f287dc7ae11d4716c3f3419/lib/server-process.js#L61) to `if (false)`? I'm wondering if maybe that error is coming from git-ssb rather than Patchwork.

**Comment by dangerousbeans** [comment]
Didn't fix :C

**Comment by christianbundy** [comment]
Does Patchwork crash when this error is logged, or does it continue running fine?

**Comment by dangerousbeans** [comment]
Keeps running but is empty of content

**Comment by dangerousbeans** [comment]
Bug was introduced somewhere in: 019348a8 I believe

**Comment by dangerousbeans** [comment]
hm was checking out old versions - but it seems to just happen randomly

**Comment by christianbundy** [comment]
Could you try `mv ~/.ssb/config ~/.ssb/config.bak` to see if a vanilla config makes any difference?

**Comment by dangerousbeans** [comment]
issue still present after moving config

**Comment by dangerousbeans** [comment]
(thanks for the A+ support btw, I know this is a pain in the ass lol)

**Comment by christianbundy** [comment]
Damn. Could you post the new config output now that you've got everything running vanilla?
