### ISSUE TITLE
SSB indexing issue 

### ISSUE THREAD

**Issue by tchoi8** [ssbc/patchwork#1157]
Hi friends

I accidentally opened Patchwork and Patchbay at the same time and finding them to indexing indefinitely. It's similar to Mary's [issue](https://github.com/ssbc/patchwork/issues/1107) but some of the errors look different.

```
TaeyoonWorkshop:.ssb taeyoon$ npm start
npm ERR! path /Users/taeyoon/.ssb/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/taeyoon/.ssb/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/taeyoon/.npm/_logs/2019-08-11T12_58_05_534Z-debug.log
 
```

So I tried to delete and resync everything following this [instruction](https://www.scuttlebutt.nz/faq/basics/delete.html) and found a list of errors.

```
TaeyoonWorkshop:~ taeyoon$ mkdir .ssb
TaeyoonWorkshop:~ taeyoon$ cp ssb_bak/.ssb/secret .ssb
TaeyoonWorkshop:~ taeyoon$ cp ssb_bak/.ssb/gossip.json .ssb
TaeyoonWorkshop:~ taeyoon$ cd .ssb
TaeyoonWorkshop:.ssb taeyoon$ ssb-server start
ssb-minimal-pub-server 15.0.1 /Users/taeyoon/.ssb logging.level:notice
my key ID: W1o0EvTFWz6rOxHl0QYuhWnCYpJ3/lnm1ZuSgUy2kQo=.ed25519
(node:1396) Warning: N-API is an experimental feature and could change at any time.
ssb-friends: stream legacy api used
Trace: deprecated api used: ssb-ref.parseAddress
    at Object.parseAddress (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/ssb-ref/index.js:96:15)
    at parseAddress (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/ssb-legacy-conn/lib/index.js:65:20)
    at validateAddr (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/ssb-legacy-conn/lib/index.js:95:54)
    at Object.add (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/ssb-legacy-conn/lib/index.js:227:49)
    at connDB.loaded.then (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/ssb-legacy-conn/lib/index.js:412:28)
    at <anonymous>
Error replicating with @QIlKZ8DMw9XpjpRZ96RBLpfkLnOUZSqamC6WMddGh3I=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/stream.js:116:17)
    at /usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/index.js:46:15
    at remoteCall (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/api.js:40:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/api.js:25:18)
    at replicate (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/ssb-replicate/legacy.js:291:13)
    at EventEmitter.fallback (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/ssb-replicate/legacy.js:351:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
Error replicating with @SP4xNZmDsOuRrjDS6NCcmr3xoieXQOMPBQ4TkUHSJ2M=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/stream.js:116:17)
    at /usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/index.js:46:15
    at remoteCall (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/api.js:40:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/api.js:25:18)
    at replicate (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/ssb-replicate/legacy.js:291:13)
    at EventEmitter.fallback (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/ssb-replicate/legacy.js:351:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
Error replicating with @nSCVHJ5OSajcynWgo3Xh0bChZN3e4oV1ooIuFWdxrmg=.ed25519: ebt:68%)
   Error: parent stream is closing
    at PacketStream.stream (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/stream.js:116:17)
    at /usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/index.js:46:15
    at remoteCall (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/api.js:40:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/muxrpc/api.js:25:18)
    at replicate (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/ssb-replicate/legacy.js:291:13)
    at EventEmitter.fallback (/usr/local/lib/node_modules/ssb-minimal-pub-server/node_modules/ssb-replicate/legacy.js:351:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)

<--- Last few GCs --->

[1396:0x103000000]   425712 ms: Mark-sweep 1344.4 (1458.3) -> 1344.3 (1458.3) MB, 1704.6 / 0.6 ms  allocation failure GC in old space requested
[1396:0x103000000]   427692 ms: Mark-sweep 1344.3 (1458.3) -> 1344.3 (1425.8) MB, 1979.7 / 1.0 ms  last resort GC in old space requested
[1396:0x103000000]   428543 ms: Mark-sweep 1344.3 (1425.8) -> 1344.3 (1425.8) MB, 851.9 / 0.6 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x330f63925879 <JSObject>
    1: from [buffer.js:~175] [pc=0x13ca0bd105c2](this=0x330f974364f1 <JSFunction Buffer (sfi = 0x330f6397c461)>,value=0x330f52cfc241 <Very long string[1863774]>,encodingOrOffset=0x330f639358e9 <String[4]: utf8>,length=0x330fd5c822d1 <undefined>)
    2: arguments adaptor frame: 2->3
    3: writeFd(aka writeFd) [fs.js:1287] [bytecode=0x330f83e09c91 offset=62](this=0x330fd5c822d1 <undefined>,fd=69,...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 7: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 8: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
 9: node::Buffer::(anonymous namespace)::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
10: 0x13ca0b8c6827
11: 0x13ca0bd105c2
12: 0x13ca0b78535f
Abort trap: 6

```

I appreciate any help and advice on the next steps. #

**Comment by tchoi8** [comment]
I tried ssb-server start few more times and it returned the same error. 
I tried opening Patchwok a few more times. It got stuck indexing.
I went to sleep and came back, opened Patchwork a few more times and now it's finished indexing. 
Perhaps this is a common rookie mistake.

**Comment by mixmix** [comment]
oh gods that guide for recovering your data made me scream "AAAAAHHH" out loud.
It's right, but I wouldn't have recommended this I don't think. It's our fault for not making better support / tools I think

Here's the PR : https://github.com/ssbc/scuttlebutt.nz/pull/143
