### ISSUE TITLE
Unexpected Error: Cannot read property '_currentElement' of null

### ISSUE THREAD

**Issue by cryptix** [ssbc/patchwork#116]
Found these in the `Issues` Tab. Can't tell you much more about this, sadly.

```
Cannot read property '_currentElement' of null

TypeError: Cannot read property '_currentElement' of null
    at Object.ReactReconciler.unmountComponent (/Users/hnry/patchwork/node_modules/react/lib/ReactReconciler.js:51:59)
    at [object Object].ReactCompositeComponentMixin.unmountComponent (/Users/hnry/patchwork/node_modules/react/lib/ReactCompositeComponent.js:246:21)
    at Object.ReactReconciler.unmountComponent (/Users/hnry/patchwork/node_modules/react/lib/ReactReconciler.js:52:22)
    at Object.ReactChildReconciler.unmountChildren (/Users/hnry/patchwork/node_modules/react/lib/ReactChildReconciler.js:115:25)
    at ReactDOMComponent.ReactMultiChild.Mixin.unmountChildren (/Users/hnry/patchwork/node_modules/react/lib/ReactMultiChild.js:398:28)
    at ReactDOMComponent.Mixin.unmountComponent (/Users/hnry/patchwork/node_modules/react/lib/ReactDOMComponent.js:911:10)
    at Object.ReactReconciler.unmountComponent (/Users/hnry/patchwork/node_modules/react/lib/ReactReconciler.js:52:22)
    at Object.ReactChildReconciler.unmountChildren (/Users/hnry/patchwork/node_modules/react/lib/ReactChildReconciler.js:115:25)
    at ReactDOMComponent.ReactMultiChild.Mixin.unmountChildren (/Users/hnry/patchwork/node_modules/react/lib/ReactMultiChild.js:398:28)
    at ReactDOMComponent.Mixin.unmountComponent (/Users/hnry/patchwork/node_modules/react/lib/ReactDOMComponent.js:911:10)
```
This was an unhandled exception.

**Comment by pfraze** [comment]
These errors are coming out of react. They usually only happen if you manually manipulate the DOM. Did you do anything with the devtools prior to them?

**Comment by cryptix** [comment]
I honestly didn't. This was on OS X 10.11.1 with Node 4.2.2.

I narrowed it down to adding an unreachable pub. (At least from my Uni "network"...)
The text below the input changed to the "Please wait..." text and then these `Issues` tab started filling up. On one occasion I couldn't get the "Join a Pub!" dialog to disappear, every click resulted in one of these `Unexpected Error: ...`s.

**Comment by pfraze** [comment]
I haven't experienced these since, or heard any more reports. Closing, re-open if you experience it.
