### ISSUE TITLE
Unexpected Error:  Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by cryptix** [ssbc/patchwork#117]
Found these in the Issues Tab. Can't tell you much more about this, sadly.

```
Cannot read property 'toLowerCase' of undefined

TypeError: Cannot read property 'toLowerCase' of undefined
    at InviteErrorExplanation.render (/Users/hnry/patchwork/ui/com/help/forms.jsx:8:37)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/hnry/patchwork/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/hnry/patchwork/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at [object Object].wrapper [as _renderValidatedComponent] (/Users/hnry/patchwork/node_modules/react/lib/ReactPerf.js:66:21)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/hnry/patchwork/node_modules/react/lib/ReactCompositeComponent.js:220:30)
    at [object Object].wrapper [as mountComponent] (/Users/hnry/patchwork/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (/Users/hnry/patchwork/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (/Users/hnry/patchwork/node_modules/react/lib/ReactMultiChild.js:474:40)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/hnry/patchwork/node_modules/react/lib/ReactMultiChild.js:378:16)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/hnry/patchwork/node_modules/react/lib/ReactMultiChild.js:326:14)
```

This was an unhandled exception.

**Comment by pfraze** [comment]
Closing as a duplicate of https://github.com/ssbc/patchwork/issues/116
