### ISSUE TITLE
AppImage runs out of memory and crashes due to 2 GM memory limit

### ISSUE THREAD

**Issue by interfect** [ssbc/patchwork#1190]
Electron imposes a 2 GB memory limit, and the 3.16.2 AppImage hits it for me:

```
<--- Last few GCs --->

[15731:0x26e877fcf000]    73461 ms: Scavenge 1960.3 (2081.2) -> 1959.5 (2081.7) MB, 8.4 / 0.0 ms  (average mu = 0.169, current mu = 0.106) allocation failure 
[15731:0x26e877fcf000]    73475 ms: Scavenge 1960.4 (2081.7) -> 1959.6 (2082.2) MB, 7.7 / 0.0 ms  (average mu = 0.169, current mu = 0.106) allocation failure 
[15731:0x26e877fcf000]    73487 ms: Scavenge 1960.6 (2082.2) -> 1959.8 (2082.7) MB, 7.1 / 0.0 ms  (average mu = 0.169, current mu = 0.106) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x555c523452ae]
    1: StubFrame [pc: 0x885c6ca03af]
Security context: 0x1ab147cc7411 <String[7]: file://>
    2: /* anonymous */ [0x15bd25095221] [/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/abstract-leveldown/abstract-iterator.js:1] [bytecode=0x897ade407c1 offset=0](this=0x38ecffa045b1 <JSGlobal Object>)
    3: arguments adaptor frame: 3->0
    4: /* anonymous */(aka /* anonymous */) [0x15bd250952a1] [...

Exception thrown by PacketStream substream end handler Error {}
Error: unexpected end of parent stream
    at PacketStream.destroy (/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/packet-stream/index.js:133:41)
    at /tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/muxrpc/pull-weird.js:58:44
    at /tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/pull-stream/sinks/drain.js:20:24
    at /tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/packet-stream-codec/index.js:98:24)
    at drain (/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/pull-reader/index.js:46:23)
    at /tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/pull-reader/index.js:63:18
    at drain (/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/stream-to-pull-stream/index.js:143:5)
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected end of parent stream
    at PacketStream.destroy (/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/packet-stream/index.js:133:41)
    at /tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/muxrpc/pull-weird.js:58:44
    at /tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/pull-stream/sinks/drain.js:20:24
    at /tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/packet-stream-codec/index.js:98:24)
    at drain (/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/pull-reader/index.js:46:23)
    at /tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/pull-reader/index.js:63:18
    at drain (/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/tmp/.mount_ssb-paEajuEf/resources/app.asar/node_modules/stream-to-pull-stream/index.js:143:5)
```

That stack trace repeats a bunch, and then the process dies.

I get much better results when I give it 4 GB of memory:

`ssb-patchwork-3.16.2-x86_64.AppImage --js-flags="--max-old-space-size=4096"`

The AppImage should run like this by default, I think. Alternately, if 2 GB of memory usage is unexpectedly high, something is making my Patchwork use too much memory.

Patchbay is having a similar problem (%1/H6AQHaV5jEZW2pDEyTpxOAi9gHBpVZVGxHHfBFzrU=.sha256).

**Comment by christianbundy** [comment]
Thanks for the bug report! Do you know what the app is doing when it crashes from high memory usage? I haven't seen this before and I'm wondering how we might reproduce the problem.

**Comment by interfect** [comment]
I think it may have been indexing the database and/or downloading messages.

September 27, 2019 10:56 PM, "Christian Bundy" <notifications@github.com (mailto:notifications@github.com?to=%22Christian%20Bundy%22%20<notifications@github.com>)> wrote:
	Thanks for the bug report! Do you know what the app is doing when it crashes from high memory usage? I haven't seen this before and I'm wondering how we might reproduce the problem.

**Comment by interfect** [comment]
I think that this may have been fixed. I've been running newer AppImage versions without any special arguments and without any crashing.

**Comment by christianbundy** [comment]
Happy to hear that!
