### ISSUE TITLE
Failing to start on chromebook

### ISSUE THREAD

**Issue by PragmaticCypher** [ssbc/patchwork#1225]
Patchwork fails with an error when I attempt to start it.  This happens both on the latest stable version and master.
```
# yarn start
Error: No native build was found for platform=linux arch=arm runtime=electron abi=73 uv=1 libc=glibc
    at Function.load.path (/home/cypher/src/patchwork/node_modules/leveldown/node_modules/node-gyp-build/index.js:56:9)
    at load (/home/cypher/src/patchwork/node_modules/leveldown/node_modules/node-gyp-build/index.js:20:30)
    at Object.<anonymous> (/home/cypher/src/patchwork/node_modules/leveldown/binding.js:1:198)
    at Object.<anonymous> (/home/cypher/src/patchwork/node_modules/leveldown/binding.js:3:3)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

**Comment by christianbundy** [comment]
Does this also happen with npm? If so, I'd be very curious to see your build logs.

**Comment by PragmaticCypher** [comment]
It does indeed, here is the gist for a build on the latest master:

https://gist.github.com/PragmaticCypher/1293f4c948c8887d33fb2ffcd3b6cdbd

**Comment by christianbundy** [comment]
Weird, I think that build looks successful, right? And then if you try to run it you get "no native modules found"? I don't think I've ever seen a successful Patchwork build that ends up with no native modules. :thinking: Which version of Node are you on? Maybe try downgrading and then retrying the build process with your new ABI? Node 10 and 12 should work, IIRC.

**Comment by PragmaticCypher** [comment]
It was strange, building everything from source with the following command fixed the issues.

```
npm install --build-from-source
```

**Comment by christianbundy** [comment]
Hmm. Maybe it's a problem with the prebuilt binaries? I'll add that command to the docs, just in case.

**Comment by PragmaticCypher** [comment]
> Hmm. Maybe it's a problem with the prebuilt binaries? I'll add that command to the docs, just in case.

Yes it seems so, the Chromebook runs on an arm processor.  Thanks for the help :+1:

**Comment by PragmaticCypher** [comment]
> Hmm. Maybe it's a problem with the prebuilt binaries? I'll add that command to the docs, just in case.

I'm one step ahead ;)
