### ISSUE TITLE
electron-prebuilt missing file error (fatal)

### ISSUE THREAD

**Issue by du5t** [ssbc/patchwork#125]
```
> ssb-patchwork@1.1.2 start /home/user/apps/patchwork
> electron .

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/user/apps/patchwork/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/home/user/apps/patchwork/node_modules/electron-prebuilt/index.js:4:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! Linux 3.13.0-68-lowlatency
npm ERR! argv "/home/user/.nvm-fish/v4.2.1/bin/node" "/home/user/.nvm-fish/v4.2.1/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! ssb-patchwork@1.1.2 start: `electron .`
npm ERR! Exit status 1
```

From b6e9ead0529e9c, clean npm install.

**Comment by du5t** [comment]
Strangely, it worked after running `npm install` inside the electron-prebuilt dir and then running `npm install` at app root.

**Comment by pfraze** [comment]
Hmm, what node version? The full steps for setup from the repo are:

```
git clone $REPO
cd patchwork
npm install -d
npm run build:ui
npm start
```

Did you vary from that? How did you start the app?

**Comment by du5t** [comment]
Yeah I varied from that. I was pulling the latest changes and neglected the `build:ui` task, so probably my bad.

**Comment by pfraze** [comment]
well `build:ui` only compiles the CSS, so that's probably not the issue.

Let's leave this one open, in case others experience it.
