### ISSUE TITLE
Patchwork arm64 AppImage fails on Pinebook Pro

### ISSUE THREAD

**Issue by sunjam** [ssbc/patchwork#1269]
Attempting to run Patchwork-3.17.6-arm64.AppImage on Manjaro ARM KDE Plasma for [Pinebook Pro](https://www.pine64.org/pinebook-pro/)

$ chmod a+x Patchwork-3.17.6-arm64.AppImage
$ pacman -S fuse2 appmenu-gtk-module
$ ./Patchwork-3.17.6-arm64.AppImage

[Here is the output](https://gist.github.com/sunjam/b8e61c6d73eb01159c90e6bc1b804ba5).
A blank Patchwork window launches.

**Comment by christianbundy** [comment]
Hmm, could you try installing from source and checking to see what breaks?

Documentation available here: https://github.com/ssbc/patchwork/blob/master/docs/INSTALL.md

**Comment by sunjam** [comment]
Thanks, building from source on Manjaro ARM worked, but the database is forever indexing and not allowing me to send messages until it finishes.

 },
  timestamp: 1584896531427
}
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected end of parent stream
    at PacketStream.destroy (/home/rock/patchwork/node_modules/packet-stream/index.js:71:7)
    at Object.ws.close (/home/rock/patchwork/node_modules/muxrpc/stream.js:136:23)
    at EventEmitter.emitter.close (/home/rock/patchwork/node_modules/muxrpc/index.js:78:8)
    at ConnHub.reset (/home/rock/patchwork/node_modules/ssb-conn-hub/lib/index.js:356:30)
    at EventEmitter.<anonymous> (/home/rock/patchwork/node_modules/ssb-conn/lib/conn-scheduler.js:136:37)
    at EventEmitter.emit (events.js:200:13)
    at /home/rock/patchwork/node_modules/on-wakeup/index.js:16:17

**Comment by sunjam** [comment]
Hmm, I let Patchwork index for a while and now it is working!  Hurray.  Let me know if any of the above information is useful.  I hope it is helpful for others installing on Arch Linux, Manjaro and ARM devices such as the Pinebook and Raspberry Pi.
