### ISSUE TITLE
Error: EEXIST: file already exists, open '/home/trav/.ssb/secret'

### ISSUE THREAD

**Issue by treasuretron** [ssbc/patchwork#1271]
Migrating from KDE Neon to ElementaryOS. Elementary is _supposed_ to be the easier distro but it really hasn't been behaving with Patchwork. Was able to install the .deb with Eddy but Patchwork fails to launch. Syslog is telling me:

```
Mar 23 10:53:01 thingus io.elementary.files.db[1283]: Error: EEXIST: file already exists, open '/home/trav/.ssb/secret'
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:     at Object.openSync (fs.js:447:3)
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:     at Object.func (electron/js2c/asar.js:138:31)
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:     at Object.func [as openSync] (electron/js2c/asar.js:138:31)
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:     at Object.writeFileSync (fs.js:1206:35)
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:     at Object.exports.createSync (/tmp/.mount_Patchw23ow2h/resources/app.asar/node_modules/ssb-keys/storage.js:104:8)
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:     at Object.exports.loadOrCreateSync (/tmp/.mount_Patchw23ow2h/resources/app.asar/node_modules/ssb-keys/index.js:89:20)
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:     at setDefaults (/tmp/.mount_Patchw23ow2h/resources/app.asar/node_modules/ssb-config/defaults.js:55:27)
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:     at module.exports (/tmp/.mount_Patchw23ow2h/resources/app.asar/node_modules/ssb-config/inject.js:7:16)
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:     at setupContext (/tmp/.mount_Patchw23ow2h/resources/app.asar/index.js:197:43)
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:     at App.<anonymous> (/tmp/.mount_Patchw23ow2h/resources/app.asar/index.js:54:3) {
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:   errno: -17,
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:   syscall: 'open',
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:   code: 'EEXIST',
Mar 23 10:53:01 thingus io.elementary.files.db[1283]:   path: '/home/trav/.ssb/secret'
Mar 23 10:53:01 thingus io.elementary.files.db[1283]: }
Mar 23 10:53:05 thingus PackageKit: get-details-local transaction /136_ceedceca from uid 1000 finished with success after 672ms
Mar 23 10:53:05 thingus PackageKit: resolve transaction /137_caadacec from uid 1000 finished with success after 483ms
```

Which, yes, true, filed does exist, I copied my .ssb folder over. I figured Patchwork would just see it and carry on as usual :)

I also don't seem to be able to call ssb-server (`Command 'ssb-server' not found`) so maybe Patchwork isn't quite installed all the way right?

I am low on sleep :p

**Comment by treasuretron** [comment]
solved it, needed to `chown -R` my .ssb :p

**Comment by treasuretron** [comment]
lol, I had this error again on my pub and the same solution worked. Here's to documentation!!
