### ISSUE TITLE
Infinite Scuttling

### ISSUE THREAD

**Issue by sunjam** [ssbc/patchwork#1274]
I'm attempting to resolve infinite scuttling on Arm64 source built Patchwork.  My goal is to update Patchwork to the latest 3.17.7 Github build and I seem to be a bit stuck.

Followed [these instructions](https://github.com/ssbc/patchwork/issues/1192#issuecomment-540863309) and now I'm seeing this error once I start Patchwork via `npm start`...
`git-ssb is not installed, or not available in path
Error: listen EADDRINUSE: address already in use 127.0.0.1:8008
    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
    at listenInCluster (net.js:1274:12)
    at doListen (net.js:1413:7)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
    at runNextTicks (internal/process/task_queues.js:59:3)
    at processImmediate (internal/timers.js:412:9)
Error: async hook stack has become corrupted (actual: 52, expected: 0)`

I [tried these instructions from a different issue](https://github.com/ssbc/patchwork/issues/1222#issuecomment-562632697) and now see:
`git-ssb is not installed, or not available in path
Error: listen EADDRINUSE: address already in use 127.0.0.1:8008
    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
    at listenInCluster (net.js:1274:12)
    at doListen (net.js:1413:7)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
    at runNextTicks (internal/process/task_queues.js:59:3)
    at processImmediate (internal/timers.js:412:9)
Error: async hook stack has become corrupted (actual: 52, expected: 0)`

**Comment by christianbundy** [comment]
That looks to me like you already have a process listening on port 8008. Could you try finding that process and stopping it, or restarting your computer?
