### ISSUE TITLE
Cannot read property 'componentDidEnter' of undefined

### ISSUE THREAD

**Issue by aredridel** [ssbc/patchwork#141]
```
TypeError: Cannot read property 'componentDidEnter' of undefined
    at [object Object].React.createClass._handleDoneEntering (/Applications/Patchwork.app/Contents/Resources/app/node_modules/react/lib/ReactTransitionGroup.js:135:18)
    at endListener (/Applications/Patchwork.app/Contents/Resources/app/node_modules/react/lib/ReactCSSTransitionGroupChild.js:86:9)

This was an unhandled exception.
```

**Comment by pfraze** [comment]
Ok this appears to be a [React issue](https://github.com/facebook/react/issues/4876) that was solved in 0.14.3, keeping this open till we've confirmed.

**Comment by aredridel** [comment]
Actually makes sense: updated react today and haven't seen it since.

**Comment by pfraze** [comment]
Hasnt happened recently, going to close.

**Comment by brettdorrans** [comment]
I am still seeing this exact error in 0.14.5.

`Uncaught TypeError: Cannot read property 'componentDidLeave' of undefined
React.createClass._handleDoneLeaving @ ReactTransitionGroup.js:166
endListener @ ReactCSSTransitionGroupChild.js:86
`
