### ISSUE TITLE
Cannot read property 'componentDidEnter' of undefined

### ISSUE THREAD

**Issue by jrf0110** [ssbc/patchwork#152]
Patchwork version `1.1.2`

```
Cannot read property 'componentDidEnter' of undefined

TypeError: Cannot read property 'componentDidEnter' of undefined
    at [object Object].React.createClass._handleDoneEntering (/Users/john/random-repos/patchwork/node_modules/react/lib/ReactTransitionGroup.js:135:18)
    at endListener (/Users/john/random-repos/patchwork/node_modules/react/lib/ReactCSSTransitionGroupChild.js:86:9)

This was an unhandled exception.
```

**Comment by pfraze** [comment]
Closing as a duplicate of https://github.com/ssbc/patchwork/issues/141

**Comment by pfraze** [comment]
Thanks for reporting

**Comment by jrf0110** [comment]
Just doing my job, ma'am.
