### ISSUE TITLE
error posting in current master

### ISSUE THREAD

**Issue by mixmix** [ssbc/patchwork#158]
_ssbMsgs2.default.relationsTo is not a function

```
TypeError: _ssbMsgs2.default.relationsTo is not a function
    at /home/mix/projects/patchwork/ui/com/msg-thread.jsx:84:29
    at /home/mix/projects/patchwork/ui/node_modules/pull-stream/sinks.js:15:33
    at /home/mix/projects/patchwork/node_modules/patchwork-threads/index.js:258:25
    at /home/mix/projects/patchwork/node_modules/multicb/index.js:40:13
    at next (/home/mix/projects/patchwork/node_modules/patchwork-threads/index.js:363:7)
    at Object._requests.(anonymous function) (/home/mix/projects/patchwork/ui/node_modules/muxrpc/node_modules/packet-stream/index.js:37:5)
    at PacketStream._onrequest (/home/mix/projects/patchwork/ui/node_modules/muxrpc/node_modules/packet-stream/index.js:139:26)
    at PacketStream.write (/home/mix/projects/patchwork/ui/node_modules/muxrpc/node_modules/packet-stream/index.js:122:41)
    at /home/mix/projects/patchwork/ui/node_modules/muxrpc/pull-weird.js:52:15
    at /home/mix/projects/patchwork/ui/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33
```

**Comment by mixmix** [comment]
@pfraze  I updated as suggested, `ssb-msgs` is at 5.2.0  

same error as before I think

**Comment by pfraze** [comment]
Are you 100% certain that 5.2.0 is being used? Im not sure what else could cause this

**Comment by mixmix** [comment]
Fairly sure. I checked packages.json in  `./` and in
`node_modules/ssb-msgs` will check again when i get home

**Comment by pfraze** [comment]
See notes in #160, lmk if fixed
