### ISSUE TITLE
module version mismatch (leveldown?)

### ISSUE THREAD

**Issue by mixmix** [ssbc/patchwork#220]
this is blocking the app starting for me in the master branch.

I've updated npm to 3.5.2 in case it was some package conflict blah, and scrapped node_modules and fresh-installed. 

Here's the error : 

```
Module version mismatch. Expected 47, got 46.
App threw an error when running [Error: Module version mismatch. Expected 47, got 46.]
/home/mix/projects/patchwork/node_modules/libsodium/dist/modules/libsodium.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filename!=nodePath["resolve"](file

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:140:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:140:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/home/mix/projects/patchwork/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/mix/projects/patchwork/node_modules/leveldown/leveldown.js:4:46)


```

**Comment by pfraze** [comment]
Nope, this is due to electron's latest now requiring v5. Explanation in https://github.com/ssbc/patchwork/pull/219
