### ISSUE TITLE
"Module version mismatch. Expected 47, got 46" on node 4.2.2

### ISSUE THREAD

**Issue by 0x00A** [ssbc/patchwork#235]
Fresh clone and `npm install` fails on `npm start`. Tried `npm rebuild` and also multiple combinations of reinstalling and bumping versions of electron. 

One possible remedy might be to make `electron` a dependency and call it directly (for example from `"start": "./node_modules/.bin/electron/bin"` instead of calling it as a global (`https://github.com/ssbc/patchwork/blob/master/package.json#L11`) 

Maybe this will be helpful...
```
(electron) ipc module is deprecated. Use require("electron").ipcMain instead.
Module version mismatch. Expected 47, got 46.
Module version mismatch. Expected 47, got 46.
App threw an error when running [Error: Module version mismatch. Expected 47, got 46.]
./patchwork/node_modules/ssb-keys/node_modules/chloride/node_modules/sodium-browserify/node_modules/libsodium-wrappers/node_modules/libsodium/dist/modules/libsodium.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:140:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:140:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (./patchwork/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (./patchwork/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level/node_modules/leveldown/leveldown.js:4:46)
```

**Comment by pfraze** [comment]
What node version are you using? You need 5.3.x

**Comment by 0x00A** [comment]
Oh! I didn't see that this changed, last i was using patchwork it only worked on 4.x. I can no longer use 4.x? 5.x is crazy slow and i have yet to use a version manager that didn't make havoc with npm

**Comment by pfraze** [comment]
Yeah, we upgraded electron and that forced the change. We're actually looking really hard at [ditching electron](https://github.com/ssbc/patchwork/pull/230) so this may be a temporary situation.

**Comment by 0x00A** [comment]
Oh interesting! ok :)
