### ISSUE TITLE
Errors on About tab of profile page

### ISSUE THREAD

**Issue by clehner** [ssbc/patchwork#244]
I get the following three errors when navigating to the About page for a user.
```
/usr/local/src/patchwork/node_modules/react/node_modules/fbjs/lib/warning.js:45
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the  component.
warning	@	/usr/local/src/patchwork/node_modules/react/node_modules/fbjs/lib/warning.js:45
warnTDZ	@	/usr/local/src/patchwork/node_modules/react/lib/ReactNoopUpdateQueue.js:18
ReactNoopUpdateQueue.enqueueSetState	@	/usr/local/src/patchwork/node_modules/react/lib/ReactNoopUpdateQueue.js:91
ReactComponent.setState	@	/usr/local/src/patchwork/node_modules/react/lib/ReactComponent.js:65
handleCB	@	user-info.jsx:30
computeState	@	user-info.jsx:227
AutoRefreshingComponent	@	user-info.jsx:32
UserInfoFlags	@	user-info.jsx:224
ReactCompositeComponentMixin.mountComponent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactCompositeComponent.js:148
wrapper	@	/usr/local/src/patchwork/node_modules/react/lib/ReactPerf.js:66
ReactReconciler.mountComponent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactReconciler.js:37
ReactMultiChild.Mixin.mountChildren	@	/usr/local/src/patchwork/node_modules/react/lib/ReactMultiChild.js:241
ReactDOMComponent.Mixin._createContentMarkup	@	/usr/local/src/patchwork/node_modules/react/lib/ReactDOMComponent.js:591
ReactDOMComponent.Mixin.mountComponent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactDOMComponent.js:479
ReactReconciler.mountComponent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactReconciler.js:37
ReactMultiChild.Mixin.mountChildren	@	/usr/local/src/patchwork/node_modules/react/lib/ReactMultiChild.js:241
ReactDOMComponent.Mixin._createContentMarkup	@	/usr/local/src/patchwork/node_modules/react/lib/ReactDOMComponent.js:591
ReactDOMComponent.Mixin.mountComponent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactDOMComponent.js:479
ReactReconciler.mountComponent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactReconciler.js:37
ReactCompositeComponentMixin.mountComponent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactCompositeComponent.js:225
wrapper	@	/usr/local/src/patchwork/node_modules/react/lib/ReactPerf.js:66
ReactReconciler.mountComponent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactReconciler.js:37
ReactCompositeComponentMixin.mountComponent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactCompositeComponent.js:225
wrapper	@	/usr/local/src/patchwork/node_modules/react/lib/ReactPerf.js:66
ReactReconciler.mountComponent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactReconciler.js:37
ReactCompositeComponentMixin._updateRenderedComponent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactCompositeComponent.js:570
ReactCompositeComponentMixin._performComponentUpdate	@	/usr/local/src/patchwork/node_modules/react/lib/ReactCompositeComponent.js:544
ReactCompositeComponentMixin.updateComponent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactCompositeComponent.js:473
wrapper	@	/usr/local/src/patchwork/node_modules/react/lib/ReactPerf.js:66
ReactCompositeComponentMixin.performUpdateIfNecessary	@	/usr/local/src/patchwork/node_modules/react/lib/ReactCompositeComponent.js:421
ReactReconciler.performUpdateIfNecessary	@	/usr/local/src/patchwork/node_modules/react/lib/ReactReconciler.js:102
runBatchedUpdates	@	/usr/local/src/patchwork/node_modules/react/lib/ReactUpdates.js:129
Mixin.perform	@	/usr/local/src/patchwork/node_modules/react/lib/Transaction.js:136
Mixin.perform	@	/usr/local/src/patchwork/node_modules/react/lib/Transaction.js:136
assign.perform	@	/usr/local/src/patchwork/node_modules/react/lib/ReactUpdates.js:86
flushBatchedUpdates	@	/usr/local/src/patchwork/node_modules/react/lib/ReactUpdates.js:147
wrapper	@	/usr/local/src/patchwork/node_modules/react/lib/ReactPerf.js:66
Mixin.closeAll	@	/usr/local/src/patchwork/node_modules/react/lib/Transaction.js:202
Mixin.perform	@	/usr/local/src/patchwork/node_modules/react/lib/Transaction.js:149
ReactDefaultBatchingStrategy.batchedUpdates	@	/usr/local/src/patchwork/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62
batchedUpdates	@	/usr/local/src/patchwork/node_modules/react/lib/ReactUpdates.js:94
ReactEventListener.dispatchEvent	@	/usr/local/src/patchwork/node_modules/react/lib/ReactEventListener.js:204
```
```
app.js:74 Unexpected Error TypeError: Cannot read property 'flaggers' of null
    at UserInfoFlags.render (/usr/local/src/patchwork/ui/com/user-info.jsx:231:32)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/usr/local/src/patchwork/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/usr/local/src/patchwork/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at [object Object].wrapper [as _renderValidatedComponent] (/usr/local/src/patchwork/node_modules/react/lib/ReactPerf.js:66:21)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/usr/local/src/patchwork/node_modules/react/lib/ReactCompositeComponent.js:220:30)
    at [object Object].wrapper [as mountComponent] (/usr/local/src/patchwork/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (/usr/local/src/patchwork/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/usr/local/src/patchwork/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/usr/local/src/patchwork/node_modules/react/lib/ReactDOMComponent.js:591:32)
    at ReactDOMComponent.Mixin.mountComponent (/usr/local/src/patchwork/node_modules/react/lib/ReactDOMComponent.js:479:29) This was an unhandled exception.addIssue @ app.js:74onError @ main.js:30
```
```
app.js:74 Unexpected Error Error: findComponentRoot(..., .0.2.0.0.0.1.0.0.$@J+0DGLgRn8H5tVLCcRUfN7NfUcTGEZKqML3krEOJjDY=0=1ed25519): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
    at invariant (/usr/local/src/patchwork/node_modules/react/node_modules/fbjs/lib/invariant.js:39:15)
    at Object.ReactMount.findComponentRoot (/usr/local/src/patchwork/node_modules/react/lib/ReactMount.js:764:54)
    at Object.ReactMount.findReactNodeByID (/usr/local/src/patchwork/node_modules/react/lib/ReactMount.js:679:23)
    at Object.getNode (/usr/local/src/patchwork/node_modules/react/lib/ReactMount.js:162:32)
    at ReactDOMComponent.Mixin._updateDOMProperties (/usr/local/src/patchwork/node_modules/react/lib/ReactDOMComponent.js:812:29)
    at ReactDOMComponent.Mixin.updateComponent (/usr/local/src/patchwork/node_modules/react/lib/ReactDOMComponent.js:699:10)
    at ReactDOMComponent.Mixin.receiveComponent (/usr/local/src/patchwork/node_modules/react/lib/ReactDOMComponent.js:645:10)
    at Object.ReactReconciler.receiveComponent (/usr/local/src/patchwork/node_modules/react/lib/ReactReconciler.js:87:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/usr/local/src/patchwork/node_modules/react/lib/ReactCompositeComponent.js:562:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/local/src/patchwork/node_modules/react/lib/ReactCompositeComponent.js:544:10) This was an unhandled exception.
```
Then the UI is in a bad state when I try to do other things I get more errors from React like
`Unexpected Error TypeError: Cannot read property '_currentElement' of null` and
`Unexpected Error TypeError: Cannot read property '_currentElement' of null`
until I refresh the page. I also get the `setState(...): Can only update a mounted or mounting component` error when entering the people page (any tab) but it doesn't break anything at that point.

**Comment by pfraze** [comment]
Fixed by reverting #226
