### ISSUE TITLE
Error: this should never happen

### ISSUE THREAD

**Issue by bhaugen** [ssbc/patchwork#245]
Two crashes in a row:

**First crash:**
```
/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/libsodium/dist/modules/libsodium.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!r

Error: this should never happen
    at /home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/pull-many/index.js:91:37
    at next (/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/pull-many/index.js:107:9)
    at read (/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/pull-many/index.js:114:40)
    at /home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/node_modules/pull-stream/throughs.js:101:14
    at start (/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/pull-paramap/index.js:36:7)
    at drain (/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/pull-paramap/index.js:23:21)
    at /home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/pull-paramap/index.js:47:13
    at Object.cb (/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/secure-scuttlebutt/index.js:307:11)
    at /home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/ssb-feed/util.js:47:12
    at Array.forEach (native)
```
**2nd crash:**
```
/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/libsodium/dist/modules/libsodium.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!r

RangeError: Maximum call stack size exceeded
    at Object.stringify (native)
    at encodePair (/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/packet-stream-codec/index.js:35:29)
    at Object.<anonymous> (/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/packet-stream-codec/index.js:81:13)
    at /home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/pull-through/index.js:56:20
    at /home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/pull-goodbye/endable.js:15:26
    at source (/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/secret-stack/node_modules/muxrpc/pull-weird.js:45:30)
    at /home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/pull-goodbye/endable.js:6:7
    at pull (/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/pull-through/index.js:49:9)
    at next (/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/looper/index.js:7:11)
    at module.exports (/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/looper/index.js:13:5)
```

**Comment by pfraze** [comment]
Yikes. Are you able to start up yet?

**Comment by bhaugen** [comment]
Net result: Patchwork can't get up again.

**Comment by pfraze** [comment]
What happens now when you try to start?

**Comment by bhaugen** [comment]
> Are you able to start up yet?

Nope.

**Comment by bhaugen** [comment]
> What happens now when you try to start?

RangeError: Maximum call stack size exceeded

**Comment by pfraze** [comment]
Ok, that's the second crash, yeah?

Did anything happen to trigger the first crash?

**Comment by bhaugen** [comment]
Possible clue: Patchwork is starting up with a right panel open on the thread.

**Comment by pfraze** [comment]
> Possible clue: Patchwork is starting up with a right panel open on the thread.

Could you elaborate? What right panel -- you mean, the notifications?

**Comment by bhaugen** [comment]
> Ok, that's the second crash, yeah?

That same error happened the third time, too.

> Did anything happen to trigger the first crash?

First crash, I had tried to scroll the right panel down to see if more replies.

> Could you elaborate? What right panel -- you mean, the notifications?

No, it was a discussion thread, not a notification. Initial post and a bunch of replies.

**Comment by bhaugen** [comment]
The 2nd and 3rd time I had not done anything. Patchwork went up, and died, without me even clicking on the window.

**Comment by pfraze** [comment]
How did you open the right panel? I believe that's some leftover code, there shouldnt be any UI element to enable it.

**Comment by bhaugen** [comment]
I'm on Ubuntu 12.04, if that matters.

**Comment by pfraze** [comment]
Hmm, though I dont know what version you're running. You might be on an older version does have the right panel

**Comment by bhaugen** [comment]
> How did you open the right panel? I believe that's some leftover code, there shouldnt be any UI element to enable it.

Patchwork came up with the right panel open. As far as I can remember, I did not have the right panel open when I quit.

> Hmm, though I dont know what version you're running. You might be on an older version does have the right panel

The version I was running did have the right panel. patchwork --version tries to open patchwork again.

**Comment by bhaugen** [comment]
New clue coming up...

**Comment by pfraze** [comment]
Try installing latest via git and running (will not lose your data)

**Comment by bhaugen** [comment]
I had been running patchwork with
 patchwork --blobs.party

If I leave off the --blobs.party, it runs ok.

**Comment by pfraze** [comment]
Wow, really? That's totally baffling

**Comment by bhaugen** [comment]
Looks like I'm ok, at least for now. Let me know if you want me to try anything else, but I'm probably off to dinner... :grin:

**Comment by pfraze** [comment]
No worries for now, we'll need to investigate
