### ISSUE TITLE
Set not available to bundled install

### ISSUE THREAD

**Issue by du5t** [ssbc/patchwork#264]
Pulled from master, rebuilt, ran build release. No dice. Happens on visiting any thread.

## log

Set is not defined
```
ReferenceError: Set is not defined
    at Object.exports.flattenThread (http://localhost:7777/main.build.js:41418:26)
    at http://localhost:7777/main.build.js:79540:44
    at http://localhost:7777/main.build.js:41584:7
    at http://localhost:7777/main.build.js:36521:13
    at http://localhost:7777/main.build.js:41611:25
    at http://localhost:7777/main.build.js:36521:13
    at http://localhost:7777/main.build.js:41656:7
    at Object._requests.(anonymous function) (http://localhost:7777/main.build.js:40824:5)
    at PacketStream._onrequest (http://localhost:7777/main.build.js:40926:26)
    at PacketStream.write (http://localhost:7777/main.build.js:40909:41)

This was an unhandled exception.
```

**Comment by pfraze** [comment]
What browser are you using?

**Comment by du5t** [comment]
this was tried with multiple flavors of both updated chromium and debranded firefox. good point tho, I always forget about the non-bleeding edge of js

**Comment by du5t** [comment]
closing-- it hasn't happened since the build process changed
