### ISSUE TITLE
Kaboom with a webcam capture

### ISSUE THREAD

**Issue by aredridel** [ssbc/patchwork#27]
Cannot read property 'width' of undefined

```
TypeError: Cannot read property 'width' of undefined
    at checkFrames (file:///Users/aredridel/Downloads/Patchwork.app/Contents/Resources/app/ui/vendor/whammy.js:234:26)
    at new toWebM (file:///Users/aredridel/Downloads/Patchwork.app/Contents/Resources/app/ui/vendor/whammy.js:14:16)
    at WhammyVideo.window.Whammy.WhammyVideo.compile (file:///Users/aredridel/Downloads/Patchwork.app/Contents/Resources/app/ui/vendor/whammy.js:519:12)
    at stopRecording (/Users/aredridel/Downloads/Patchwork.app/Contents/Resources/app/ui/lib/com/webcam-giffer-form.js:252:20)
    at HTMLDocument.onmouseup (/Users/aredridel/Downloads/Patchwork.app/Contents/Resources/app/ui/lib/com/webcam-giffer-form.js:84:5)
```

This was an unhandled exception.

**Comment by pfraze** [comment]
Thanks for filing, was able to reproduce. Fixing now.

**Comment by pfraze** [comment]
Fixed in https://github.com/ssbc/patchwork/commit/aa864e01d011e42f3f1006f2f6ae3387653bd136

@aredridel I'm looking at how to setup electron's auto-updating, and whether I'd be comfortable with the phone-home aspect of that. In the mean time, you can redownload the package in that gist (for this one silly fix) as I did update the zip, or get PW via git so you can update that way (instructions in readme).

If you want to avoid the bug in your build, just make sure to record long enough to capture frames :expressionless:
