### ISSUE TITLE
uglify throws hard-to-trace error on build

### ISSUE THREAD

**Issue by du5t** [ssbc/patchwork#271]
appeared in 21349f6625349941 (according to `git bisect` and `npm run build-release:js`)

this is in node v5.4.1, npm 3.5.3 (and one older npm3)

Log:
```
$ npm run build-release:js

> ssb-patchwork@2.1.1 build-release:js /home/nervous/unisync/tools/apps/patchwork
> NODE_ENV=production node ./scripts/build.js ./ui/main.js ./ui/main.build.js && ./node_modules/uglify-js/bin/uglifyjs ui/main.build.js > ui/main.build.min.js; mv ui/main.build.min.js ui/main.build.js

Parse error at ui/main.build.js:41474,28
Unexpected token: operator (>)
Error
    at new JS_Parse_Error (eval at <anonymous> (/home/user/tools/apps/patchwork/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/home/user/tools/apps/patchwork/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/home/user/tools/apps/patchwork/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2025:9)
    at token_error (eval at <anonymous> (/home/user/tools/apps/patchwork/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2033:9)
    at unexpected (eval at <anonymous> (/home/user/tools/apps/patchwork/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2039:9)
    at expr_atom (eval at <anonymous> (/home/user/tools/apps/patchwork/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2546:9)
    at maybe_unary (eval at <anonymous> (/home/user/tools/apps/patchwork/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2708:19)
    at expr_ops (eval at <anonymous> (/home/user/tools/apps/patchwork/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2743:24)
    at maybe_conditional (eval at <anonymous> (/home/user/tools/apps/patchwork/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2748:20)
    at maybe_assign (eval at <anonymous> (/home/user/tools/apps/patchwork/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2772:20)
```

**Comment by du5t** [comment]
https://github.com/mishoo/UglifyJS2/issues/659

**Comment by pfraze** [comment]
Not sure why you're getting this and I dont. The build-step prior to uglify should convert the code to es5.

**Comment by du5t** [comment]
It might have been npm getting itself into a bad state--deleting and rebuilding from scratch made it go away for now.

**Comment by du5t** [comment]
info: ran into it again after rebasing to catch up.

**Comment by du5t** [comment]
It's definitely choking on the ES6 in `patchwork-threads`. If I take out all the fat arrows and replace them with ES5 lambdas, the error changes:

```
Parse error at -:41994,16
Unexpected token name «of», expected punc «;»
```

**Comment by pfraze** [comment]
@du5t oh, good find. I'll fix that

**Comment by pfraze** [comment]
@du5t this has been sitting on my todo list forever, sorry for the wait. Now that I'm looking, I don't see any es6 in patchwork-threads. Can you point me at it?

**Comment by du5t** [comment]
Yeah I don't see any left either. I think I removed any from my revision also.

**Comment by mmckegg** [comment]
Looks resolved? Closing!
