### ISSUE TITLE
Error: Cannot find module 'mdast'

### ISSUE THREAD

**Issue by bhaugen** [ssbc/patchwork#277]
This is after redoing 
npm install ssb-patchwork -g

$ patchwork
Cannot find module 'chloridedown/build/Release/sodium'
[CFG] Password: NO.
[CFG] TLS: NO.
[CFG] Remote Access: NO.
Starting...
/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/libsodium/dist/modules/libsodium.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!r

Error: Cannot find module 'mdast'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/bob/.nvm/versions/node/v5.4.0/lib/node_modules/ssb-patchwork/node_modules/mdmanifest/index.js:2:13)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

**Comment by bhaugen** [comment]
This seems to have resolved itself this morning. Wonder if it was related to the github outages?

**Comment by pfraze** [comment]
hmm, or the npm weirdness
