### ISSUE TITLE
Copy link fails in electron

### ISSUE THREAD

**Issue by clehner** [ssbc/patchwork#284]
In patchwork-electron, clicking "Copy ID" on a message card causes an error:
```
Error: prompt() is and will not be supported.
    at window.prompt (/opt/ssb-patchwork-electron/resources/atom.asar/renderer/lib/override.js:153:11)
    at Card.copyLink (http://localhost:7777/main.build.js:52:23153)
    at Card.onSelectDropdown (http://localhost:7777/main.build.js:52:22882)
    at DropdownBtn.onSelect (http://localhost:7777/main.build.js:47:22900)
    at http://localhost:7777/main.build.js:47:21964
    at Object.invokeGuardedCallback (http://localhost:7777/main.build.js:37:29345)
    at executeDispatch (http://localhost:7777/main.build.js:32:29332)
    at Object.executeDispatchesInOrder (http://localhost:7777/main.build.js:32:29722)
    at executeDispatchesAndRelease (http://localhost:7777/main.build.js:32:17938)
    at executeDispatchesAndReleaseTopLevel (http://localhost:7777/main.build.js:32:18198)
```
Ideas for fixing:
- require electron clipboard in a try-catch and use it if it's available
- factor out clipboard stuff into somewhere
- show a HTML prompt instead of using prompt()

**Comment by pfraze** [comment]
I think there may be a way in browserland to put things into the clipboard now. We should look into it.

**Comment by pfraze** [comment]
This got solved by @mixmix !
