### ISSUE TITLE
cb called twice from local api

### ISSUE THREAD

**Issue by noffle** [ssbc/patchwork#312]
Patchwork died when I clicked on a link and saw

```
NotFoundError: Key not found in database
    at /home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/secure-scuttlebutt/node_modules/level-sublevel/shell.js:101:18
    at /home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/secure-scuttlebutt/node_modules/level-sublevel/nut.js:120:19
```

followed by

```
stream is closed
```

It left the following stack trace:

```
/home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/packet-stream/index.js:150
        if(once) throw new Error('cb called twice from local api')
                 ^

Error: cb called twice from local api
    at /home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/packet-stream/index.js:150:24
    at /home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/muxrpc/stream.js:41:22
    at done (/home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/secure-scuttlebutt/index.js:524:7)
    at /home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/secure-scuttlebutt/index.js:502:9
    at /home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/secure-scuttlebutt/node_modules/pull-stream/maybe.js:41:9
    at /home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/secure-scuttlebutt/node_modules/pull-stream/sinks.js:11:20
    at drain (/home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/pull-paramap/index.js:26:11)
    at /home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/pull-paramap/index.js:65:7
    at next (/home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/secure-scuttlebutt/node_modules/pull-stream/sinks.js:7:7)
    at /home/stephen/npm/lib/node_modules/ssb-patchwork/node_modules/secure-scuttlebutt/node_modules/pull-stream/sinks.js:20:11
```

I can reproduce this by following

```
http://localhost:7777/#/msg/%25wCBZAsg5oVlbUPGYyZk7ZhVIYrX6IqGMXmPgtQAEj30%3D.sha256
```

on my browser.

**Comment by pfraze** [comment]
The stack-trace is the same as was given in #321

**Comment by mmckegg** [comment]
Not updated in 9 months, closing!
