### ISSUE TITLE
Issue when 'digging' a post

### ISSUE THREAD

**Issue by niceking** [ssbc/patchwork#317]
Tried to "dig" a post on a user's profile and it generated this, running Patchwork 2.6.0

_this6.props.onToggleStar is not a function

TypeError: _this6.props.onToggleStar is not a function
    at Object.onClick (http://localhost:7777/main.build.js:50:6125)
    at DigBtn.onClick (http://localhost:7777/main.build.js:49:26630)
    at Object.invokeGuardedCallback (http://localhost:7777/main.build.js:36:2861)
    at executeDispatch (http://localhost:7777/main.build.js:31:20447)
    at Object.executeDispatchesInOrder (http://localhost:7777/main.build.js:31:20837)
    at executeDispatchesAndRelease (http://localhost:7777/main.build.js:31:9722)
    at executeDispatchesAndReleaseTopLevel (http://localhost:7777/main.build.js:31:9982)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:7777/main.build.js:39:28127)
    at Object.EventPluginHub.processEventQueue (http://localhost:7777/main.build.js:31:13029)

This was an unhandled exception.

**Comment by pfraze** [comment]
I *just* experienced this. It occurs only when you use the dig-button on profile pages. I'll include a fix in tonight's 2.6.1 release.

Thanks (and sorry)!

**Comment by pfraze** [comment]
Fixed in 2.6.1
