### ISSUE TITLE
_nearly_ works on windows

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#320]
I tried the latest patchwork on windows.
It runs for a bit then crashes with this error:

```
Starting...
Log level: notice
Serving at http://localhost:7777

C:\Users\admin\AppData\Roaming\npm\node_modules\ssb-patchwork\node_modules\libsodium\dist\modules\libsodium.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&f
 UsageError: .0 of param dest must be of type "id|filter"
    at Error.ZE (C:\Users\admin\AppData\Roaming\npm\node_modules\ssb-patchwork\node_modules\zerr\index.js:11:42)
    at ZError (C:\Users\admin\AppData\Roaming\npm\node_modules\ssb-patchwork\node_modules\zerr\index.js:13:14)
    at Object.module.exports.valid.linksOpts (C:\Users\admin\AppData\Roaming\npm\node_modules\ssb-patchwork\node_modules\scuttlebot\lib\validators.js:148:14)
    at validate (C:\Users\admin\AppData\Roaming\npm\node_modules\ssb-patchwork\node_modules\muxrpc-validation\index.js:130:15)
    at EventEmitter.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\ssb-patchwork\node_modules\muxrpc-validation\index.js:91:17)
    at EventEmitter.hooked [as links] (C:\Users\admin\AppData\Roaming\npm\node_modules\ssb-patchwork\node_modules\hoox\index.js:10:15)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\ssb-patchwork\node_modules\scuttlebot\plugins\blobs\quota.js:33:14
    at C:\Users\admin\AppData\Roaming\npm\node_modules\ssb-patchwork\node_modules\pull-paramap\index.js:44:11
    at C:\Users\admin\AppData\Roaming\npm\node_modules\ssb-patchwork\node_modules\pull-cat\index.js:35:13
    at callback (C:\Users\admin\AppData\Roaming\npm\node_modules\ssb-patchwork\node_modules\multiblob\node_modules\pull-pushable\index.js:12:5)
```

I was able to load the UI in firefox, but couldn't keep it up for long enough to post a celebratory message, but was able to take this screenshot:

![patchwork-on-windows](https://cloud.githubusercontent.com/assets/259374/13546708/0d763a5c-e31b-11e5-9fbe-000c602d4075.PNG)

I did succeed in replicating some messages, though!
so a little bit of bug fixing and we'll be on windows.
(this is running with js crypto, but it's running)

**Comment by pfraze** [comment]
@dominictarr cool. Is this an issue that needs to stay open?

**Comment by dominictarr** [comment]
@pfraze yes, I think we can fix this and have a working thing on windows.

**Comment by substack** [comment]
I'm getting the same error on linux:

```
Serving at http://localhost:7777
[notifier] Notification daemon not available
UsageError: .0 of param dest must be of type "id|filter"
    at Error.ZE (/home/substack/projects/patchwork/node_modules/zerr/index.js:11:42)
    at ZError (/home/substack/projects/patchwork/node_modules/zerr/index.js:13:14)
    at Object.module.exports.valid.linksOpts (/home/substack/projects/patchwork/node_modules/scu
ttlebot/lib/validators.js:150:14)
    at validate (/home/substack/projects/patchwork/node_modules/muxrpc-validation/index.js:130:1
5)
    at EventEmitter.<anonymous> (/home/substack/projects/patchwork/node_modules/muxrpc-validatio
n/index.js:91:17)
    at EventEmitter.hooked [as links] (/home/substack/projects/patchwork/node_modules/hoox/index
.js:10:15)
    at /home/substack/projects/patchwork/node_modules/scuttlebot/plugins/blobs/quota.js:33:14
    at /home/substack/projects/patchwork/node_modules/pull-paramap/index.js:44:11
    at /home/substack/projects/patchwork/node_modules/pull-cat/index.js:42:13
    at drain (/home/substack/projects/patchwork/node_modules/pull-paramap/index.js:22:11)

```

**Comment by dominictarr** [comment]
Oh I got this the other day when and it was that the frist argument was actually "@blob" or something, it would probably help a lot if the error library actually said what it got, as well as what it expected.

**Comment by ahdinosaur** [comment]
hey. i'm closing this since stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).

in other news we magically [just got `v3` to build on windows](http://viewer.scuttlebot.io/%25%2BSBr3lvHbR2yNKASU7FfLX7fTN06yk4ON1qUipaG9fk%3D.sha256)! :tada:
