### ISSUE TITLE
TypeError with scuttlebot@async-validation

### ISSUE THREAD

**Issue by clehner** [ssbc/patchwork#363]
I got this error when trying to dig something or follow someone, on ssbc/scuttlebot#338. I'm guessing it means that a method is missing a validation string somewhere.
```
token.split is not a function

TypeError: token.split is not a function
    at parse (/usr/local/src/scuttlebot/node_modules/muxrpc-validation/index.js:159:16)
    at validate (/usr/local/src/scuttlebot/node_modules/muxrpc-validation/index.js:115:19)
    at Object.<anonymous> (/usr/local/src/scuttlebot/node_modules/muxrpc-validation/index.js:78:17)
    at Object.hooked (/usr/local/src/secret-stack/node_modules/hoox/index.js:10:15)
    at Object.localCall (/usr/local/src/patchwork/node_modules/muxrpc/local-api.js:31:31)
    at Object.<anonymous> (/usr/local/src/patchwork/node_modules/muxrpc/local-api.js:37:22)
    at Object.PacketStream.request (/usr/local/src/patchwork/node_modules/muxrpc/stream.js:44:17)
    at PacketStream._onrequest (/usr/local/src/patchwork/node_modules/muxrpc/node_modules/packet-stream/index.js:149:17)
    at PacketStream.write (/usr/local/src/patchwork/node_modules/muxrpc/node_modules/packet-stream/index.js:122:41)
    at /usr/local/src/patchwork/node_modules/muxrpc/pull-weird.js:56:15

Profile view onToggleFollow
```

**Comment by mmckegg** [comment]
No update in 8 months. Closing!
