### ISSUE TITLE
search box poops when called with empty result

### ISSUE THREAD

**Issue by du5t** [ssbc/patchwork#367]
simple input guard issue. strike "enter" when search box is empty and receive <del>bacon</del> stacktrace:

```
Cannot read property 'getSelectedResult' of undefined

TypeError: Cannot read property 'getSelectedResult' of undefined
    at SearchPalette.onSearch (http://localhost:7777/main.build.js:51:23694)
    at SearchPalette.onKeyDown (http://localhost:7777/main.build.js:51:23380)
    at Object.invokeGuardedCallback (http://localhost:7777/main.build.js:36:9773)
    at executeDispatch (http://localhost:7777/main.build.js:31:27161)
    at Object.executeDispatchesInOrder (http://localhost:7777/main.build.js:31:27648)
    at executeDispatchesAndRelease (http://localhost:7777/main.build.js:31:16436)
    at executeDispatchesAndReleaseTopLevel (http://localhost:7777/main.build.js:31:16696)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:7777/main.build.js:40:3229)
    at Object.EventPluginHub.processEventQueue (http://localhost:7777/main.build.js:31:19743)
```

This was an unhandled exception.

**Comment by ahdinosaur** [comment]
hey. i'm closing this since stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).
