### ISSUE TITLE
socket.addEventListener is not a function

### ISSUE THREAD

**Issue by pfrazee** [ssbc/patchwork#375]
Reported crash bug:

```
TypeError: socket.addEventListener is not a function
    at Function.module.exports [as source] (http://localhost:7777/main.build.js:33245:10)
    at duplex (http://localhost:7777/main.build.js:33127:21)
    at Object.exports.connect (http://localhost:7777/main.build.js:33098:12)
    at module.exports (http://localhost:7777/main.build.js:64416:19)
    at Object.421../favicon (http://localhost:7777/main.build.js:63912:8)
    at s (http://localhost:7777/main.build.js:1:254)
    at http://localhost:7777/main.build.js:1:305
    at Object.426../lib/app (http://localhost:7777/main.build.js:64439:14)
    at s (http://localhost:7777/main.build.js:1:254)
    at e (http://localhost:7777/main.build.js:1:425)
```

**Comment by kyrias** [comment]
And all of a sudden it started working again for me.  This is strange.

**Comment by pfraze** [comment]
hmm!

**Comment by mmckegg** [comment]
Not updated in 9 months. Closing!
