### ISSUE TITLE
suddenly recalcitrant threads

### ISSUE THREAD

**Issue by du5t** [ssbc/patchwork#387]
patchwork at 370f3c6

![busted-threads](https://cloud.githubusercontent.com/assets/14898482/15461974/262568ca-2074-11e6-9cb9-bec05ffb4efe.png)

upon clicking either of these, thread loading state continues indefinitely, with issue alert:

```
Cannot read property 'link' of null

TypeError: Cannot read property 'link' of null
    at isaReplyTo (http://localhost:7777/main.build.js:53:27938)
    at http://localhost:7777/main.build.js:53:27668
    at Array.forEach (native)
    at countReplies (http://localhost:7777/main.build.js:53:27616)
    at Card.renderPost (http://localhost:7777/main.build.js:50:18944)
    at Card.render (http://localhost:7777/main.build.js:50:15714)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (http://localhost:7777/main.build.js:33:31143)
    at ReactCompositeComponentMixin._renderValidatedComponent (http://localhost:7777/main.build.js:33:31423)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:7777/main.build.js:33:23578)
    at Object.ReactReconciler.mountComponent (http://localhost:7777/main.build.js:38:7039)

This was an unhandled exception.

```

**Comment by dominictarr** [comment]
for reference, message ids are

%5S2dUHTMdRRgqbUt4F4fGJhccGnSLe3z+p5HMzVRMaw=.sha256
%pgNw1a+uuyeuOisK1JnJ9idh2S4FloxTXczJNqOhM1o=.sha256

`    at isaReplyTo (http://localhost:7777/main.build.js:53:27938)`
hmm, is that in patchwork-threads?

that would be here: https://github.com/ssbc/patchwork-threads/blob/master/index.js#L490-L495
except there is no `.link` anywhere to be seen. @du5t `npm ls patchwork-threads` maybe you have an old version (I can open those threads just fine, btw) I'm on `patchwork-threads@2.2.0`

**Comment by du5t** [comment]
yup, 2.2.0 installed

**Comment by cryptix** [comment]
I also saw this crash but only once.

**Comment by dominictarr** [comment]
@du5t okay well it doesn't really make sense from the stack trace, because there is no link property in that file. although, further down that path there is 
```
function indexLinksTo (msgA, msgB, each) {
  if (!msgA || !msgB || !msgB.key)
    return
  exports.indexLinks(msgA, function (l, rel) {
    if (l.link === msgB.key)
      each(l, rel)
  })
}
```

it could also be this line: https://github.com/ssbc/ssb-msgs/blob/master/index.js#L95

@du5t I think you better show us what is at `main.build.js:53:27938`

**Comment by mmckegg** [comment]
Not updated recently - maybe okay now? Gonna close this.
