### ISSUE TITLE
chrome on ubuntu 16.04 showing errors

### ISSUE THREAD

**Issue by slothbag** [ssbc/patchwork#388]
I wasn't really getting any errors in windows.. but Ubuntu 16.04 chrome seems to be throwing some errors on certain pages.

undefined is not a function

TypeError: undefined is not a function
    at Card.checkOversized (http://192.168.0.76:7777/main.build.js:27199:13)
    at Card.componentDidMount (http://192.168.0.76:7777/main.build.js:27171:12)
    at CallbackQueue.assign.notifyAll (http://192.168.0.76:7777/main.build.js:39697:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (http://192.168.0.76:7777/main.build.js:51989:26)
    at ReactReconcileTransaction.Mixin.closeAll (http://192.168.0.76:7777/main.build.js:55233:25)
    at ReactReconcileTransaction.Mixin.perform (http://192.168.0.76:7777/main.build.js:55180:16)
    at ReactUpdatesFlushTransaction.Mixin.perform (http://192.168.0.76:7777/main.build.js:55167:20)
    at ReactUpdatesFlushTransaction.assign.perform (http://192.168.0.76:7777/main.build.js:53232:38)
    at Object.flushBatchedUpdates (http://192.168.0.76:7777/main.build.js:53293:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (http://192.168.0.76:7777/main.build.js:55233:25)

This was an unhandled exception.

**Comment by dominictarr** [comment]
@slothbag was it otherwise working fine, or did it not work and show this error?

**Comment by slothbag** [comment]
It showed the error pretty much straight away, 50% of the UI was functional..

**Comment by ahdinosaur** [comment]
hey. i'm closing this as stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).

if it's still a problem, open again!
