### ISSUE TITLE
While viewing someone's profile page (whom I'm not following), `TypeError: Cannot read property 'link' of null` error 

### ISSUE THREAD

**Issue by number5** [ssbc/patchwork#393]
While viewing someone's profile page (whom I'm not following), `TypeError: Cannot read property 'link' of null` error appeared in the Issues, and Activity tab showing `Loading`

```
TypeError: Cannot read property 'link' of null
    at Notification.renderContact (http://localhost:7777/main.build.js:27686:50)
    at Notification.renderContent (http://localhost:7777/main.build.js:27625:23)
    at Notification.render (http://localhost:7777/main.build.js:27585:26)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (http://localhost:7777/main.build.js:44865:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (http://localhost:7777/main.build.js:44885:32)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:7777/main.build.js:44498:30)
    at Object.ReactReconciler.mountComponent (http://localhost:7777/main.build.js:51902:35)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:7777/main.build.js:44503:34)
    at Object.ReactReconciler.mountComponent (http://localhost:7777/main.build.js:51902:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (http://localhost:7777/main.build.js:50849:40)
```
This was an unhandled exception.

I'm using Patchwork 2.8.4 for Mac

**Comment by tiagocpontesp** [comment]
+1 linux.

**Comment by dominictarr** [comment]
@clehner is this the same thing as you where getting in git-ssb?

**Comment by clehner** [comment]
@dominictarr no, this is something else. i'm looking into it now

**Comment by clehner** [comment]
@number5 @tiagocpontesp are there any particular profile pages where you see this?

**Comment by number5** [comment]
@clehner sorry I don't remember who's profile causing this issue, but I only see this once

**Comment by clehner** [comment]
ok, no problem. i found where the issue is and am fixing it now
