### ISSUE TITLE
When viewing activity profile of a new web user from patchbay

### ISSUE THREAD

**Issue by dangerousbeans** [ssbc/patchwork#406]
Cannot read property 'link' of null

TypeError: Cannot read property 'link' of null
    at Notification.renderContact (http://localhost:7777/main.build.js:27686:50)
    at Notification.renderContent (http://localhost:7777/main.build.js:27625:23)
    at Notification.render (http://localhost:7777/main.build.js:27585:26)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:7777/main.build.js:44865:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:7777/main.build.js:44885:32)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:7777/main.build.js:44498:30)
    at Object.mountComponent (http://localhost:7777/main.build.js:51902:35)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:7777/main.build.js:44503:34)
    at Object.mountComponent (http://localhost:7777/main.build.js:51902:35)
    at ReactDOMComponent._mountChildByNameAtIndex (http://localhost:7777/main.build.js:50849:40)

This was an unhandled exception.

**Comment by clehner** [comment]
This looks like #393. What version of Patchwork are you running?

**Comment by dominictarr** [comment]
confirmed for this account
http://localhost:7777/#/profile/%40DAXlFnGpgxBq8k1ODDoTGoaQR%2FWKl7skygyRz9XR8yg%3D.ed25519

**Comment by dangerousbeans** [comment]
@clehner I'm normally on 2.8.4, but it happens on master too with the above account

**Comment by dominictarr** [comment]
oh, latest sync has fixed my link above.
i see this issue was fix 3 weeks ago https://github.com/ssbc/patchwork/issues/393
ah but the problem is patchkit-msg-view is not published. npm still shows it's only up to 1.1.0

**Comment by dominictarr** [comment]
sorry, that isn't right... my npm show was giving me wrong result

**Comment by dominictarr** [comment]
okay, confirmed, updating to patchkit-msg-view@1.2.0 fixes this

**Comment by ahdinosaur** [comment]
hey. i'm closing this since stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).
