### ISSUE TITLE
Crash possibly caused by malformed invite

### ISSUE THREAD

**Issue by voxadam** [ssbc/patchwork#410]
I'm not 100% positive but I _think_ this crash may have been due to my entering a malformed invite code.

```
~/ 15h 36m 43s
❯ patchwork
[CFG] Password: NO.
[CFG] TLS: NO.
[CFG] Remote Access: NO.
Patchwork - Copyright (C) 2015-2016 Secure Scuttlebutt Consortium
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions (GPL-3.0).

Starting...
Loading plugins from /home/adam/.ssb/node_modules
Log level: notice
Serving at http://localhost:7777
Log history read...
Indexes generated
Connect attempt ssb.example.com:8008:@XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.ed25519
+connected ssb.celehner.com:8008:@XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=.ed25519
UsageError: Param 0 is required
    at Error.ZE (/usr/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/node_modules/zerr/index.js:11:42)
    at Object.ZError [as MissingParam] (/usr/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/node_modules/zerr/index.js:13:14)
    at validate (/usr/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/node_modules/muxrpc-validation/index.js:122:48)
    at Object.<anonymous> (/usr/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/node_modules/muxrpc-validation/index.js:58:17)
    at Object.<anonymous> (/usr/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/node_modules/secret-stack/util.js:80:17)
    at Object.<anonymous> (/usr/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/node_modules/secret-stack/node_modules/hoox/index.js:3:17)
    at Object.hooked [as add] (/usr/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/node_modules/secret-stack/node_modules/hoox/index.js:10:15)
    at /usr/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/plugins/invite.js:220:49
    at Object._requests.(anonymous function) (/usr/lib/node_modules/ssb-patchwork/node_modules/muxrpc/node_modules/packet-stream/index.js:37:5)
    at PacketStream._onrequest (/usr/lib/node_modules/ssb-patchwork/node_modules/muxrpc/node_modules/packet-stream/index.js:139:26)

~/ 1h 9m 42s
❯ 
```

**Comment by ahdinosaur** [comment]
hey. i'm closing this as stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).

if it's still a problem, open again!
