### ISSUE TITLE
range error on opening private msgs

### ISSUE THREAD

**Issue by du5t** [ssbc/patchwork#412]
@dominictarr this error occurs when i try to open our last private thread from patchwork.

```
[CFG] Password: NO.
[CFG] TLS: NO.
[CFG] Remote Access: NO.
Patchwork - Copyright (C) 2015-2016 Secure Scuttlebutt Consortium
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions (GPL-3.0).

Starting...
Loading plugins from .ssb/node_modules
Loading plugin "ssb-links"
Loading plugin "ssb-query"
Loading plugin "ssb-ws"
Log level: notice
insufficient configuration for letsencrypte
falling back to regular http
Serving at http://localhost:7777
RELOAD INDEX: {"version":5,"since":1472419629399}
LOAD LINKS SINCE null 1472419629399
RELOAD INDEX: {"version":13,"since":1472419629399}

----
CONNECTION METADATA SCRUBBED KTHX
----

Indexes generated
RangeError: out of range index
    at RangeError (native)
    at fastCopy (apps/patchwork/node_modules/ws/lib/Receiver.js:318:24)
    at Receiver.add (apps/patchwork/node_modules/ws/lib/Receiver.js:78:3)
    at Socket.firstHandler (apps/patchwork/node_modules/ws/lib/WebSocket.js:718:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

npm ERR! Linux 3.13.0-92-lowlatency
npm ERR! argv "n/bin/node" "n/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ssb-patchwork@2.10.1 start: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssb-patchwork@2.10.1 start script 'node ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ssb-patchwork package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ssb-patchwork
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ssb-patchwork
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     apps/patchwork/npm-debug.log
```

**Comment by du5t** [comment]
not sure if error log was redirected properly, so here's the same error reproduced log:

```
LOAD LINKS SINCE null 1472419629399
..(node:14148) Warning: Possible EventEmitter memory leak detected. 11 edge listeners added. Use emitter.setMaxListeners() to increase limit
packet-stream asked to read after closed { value: false, end: false, req: -172 }
RangeError: out of range index
    at RangeError (native)
    at fastCopy (apps/patchwork/node_modules/ws/lib/Receiver.js:318:24)
    at Receiver.add (apps/patchwork/node_modules/ws/lib/Receiver.js:78:3)
    at Socket.firstHandler (apps/patchwork/node_modules/ws/lib/WebSocket.js:718:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

npm ERR! Linux 3.13.0-92-lowlatency
npm ERR! argv "n/bin/node" "n/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ssb-patchwork@2.10.1 start: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssb-patchwork@2.10.1 start script 'node ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ssb-patchwork package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ssb-patchwork
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ssb-patchwork
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     apps/patchwork/npm-debug.log
```

**Comment by dominictarr** [comment]
am guessing it's probably related to https://github.com/ssbc/patchwork-threads/issues/11

**Comment by benhylau** [comment]
I hit this one too:
```
RangeError: out of range index
    at RangeError (native)
    at fastCopy (/Users/benedict/.nvm/versions/node/v6.4.0/lib/node_modules/ssb-patchwork/node_modules/ws/lib/Receiver.js:318:24)
    at Receiver.add (/Users/benedict/.nvm/versions/node/v6.4.0/lib/node_modules/ssb-patchwork/node_modules/ws/lib/Receiver.js:78:3)
    at Socket.firstHandler (/Users/benedict/.nvm/versions/node/v6.4.0/lib/node_modules/ssb-patchwork/node_modules/ws/lib/WebSocket.js:718:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
```

**Comment by olizilla** [comment]
I'm hitting this in the current [v2.12.3](https://github.com/ssbc/patchwork/releases/tag/v2.12.3) release

```
RangeError: out of range index
    at RangeError (native)
    at fastCopy (/usr/local/lib/node_modules/ssb-patchwork/node_modules/ws/lib/Receiver.js:318:24)
    at Receiver.add (/usr/local/lib/node_modules/ssb-patchwork/node_modules/ws/lib/Receiver.js:78:3)
    at Socket.firstHandler (/usr/local/lib/node_modules/ssb-patchwork/node_modules/ws/lib/WebSocket.js:718:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

**Comment by olizilla** [comment]
It's not related to opening private messages, or at lease, I seem to trigger this error just clicking around in patchwork and it occurs at different places each time. The last one was selecting a channel from the dropdown that appears if I click on the folder beneath the **Activitiy Feed** link on the left side.

**Comment by ahdinosaur** [comment]
hey. i'm closing this as stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).

if it's still a problem, open again!
