### ISSUE TITLE
Unhandled exception - callback not provided

### ISSUE THREAD

**Issue by Insoleet** [ssbc/patchwork#415]
Hello,

I'm trying to get patchwork running correctly but I can't.

With a fresh install from npm, when I add my invite code to some pub, I get the following issue and it fails : 

```
callback not provided

Error: callback not provided
noop@http://localhost:7777/main.build.js:19866:18
[154]</PacketStream.prototype.request/this._requests[rid]@http://localhost:7777/main.build.js:22004:5
[154]</PacketStream.prototype._onrequest@http://localhost:7777/main.build.js:22106:7
[154]</PacketStream.prototype.write@http://localhost:7777/main.build.js:22089:36
[141]</module.exports/<.sink/<@http://localhost:7777/main.build.js:20822:9
next/<@http://localhost:7777/main.build.js:20138:37
[293]</</exports.filter/next/<@http://localhost:7777/main.build.js:34419:9
[287]</</exports.filter/next/<@http://localhost:7777/main.build.js:33873:9
[287]</</exports.map/</<@http://localhost:7777/main.build.js:33797:7
pull@http://localhost:7777/main.build.js:34719:22
next@http://localhost:7777/main.build.js:8408:7
next/<@http://localhost:7777/main.build.js:8410:18
[294]</module.exports/</</pull/<@http://localhost:7777/main.build.js:34735:13
[300]</module.exports/<@http://localhost:7777/main.build.js:34939:14

  Error: pull-reader: read exceeded timeout
    at null._onTimeout (/home/inso/.nvm/versions/node/v5.3.0/lib/node_modules/ssb-patchwork/node_modules/pull-reader/index.js:16:10)
    at Timer.listOnTimeout (timers.js:92:15)

This was an unhandled exception.
```

Any idea ?

**Comment by ahdinosaur** [comment]
hey. i'm closing this since stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).

if it's still a problem, open again!
