### ISSUE TITLE
tests - Error: Cannot find module 'scuttlebot/plugins/blobs'

### ISSUE THREAD

**Issue by kumavis** [ssbc/patchwork#429]
```
╭─kumavis@xyzs-MacBook-Pro  ~/dev/patchwork ‹node-v6.3.1›  (master) 
╰─$ npm test

> ssb-patchwork@2.12.3 test /Users/kumavis/dev/patchwork
> set -e; for t in api/test/*.js; do node $t; done

module.js:442
    throw err;
    ^

Error: Cannot find module 'scuttlebot/plugins/blobs'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kumavis/dev/patchwork/api/test/util.js:13:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by kumavis** [comment]
```
╭─kumavis@xyzs-MacBook-Pro  ~/dev/patchwork ‹node-v6.3.1›  (master) 
╰─$ ls -la ./node_modules/scuttlebot/plugins/
total 168
drwxr-xr-x  19 kumavis  staff   646 Nov 16 14:14 .
drwxr-xr-x  14 kumavis  staff   476 Nov 16 14:14 ..
-rw-r--r--   1 kumavis  staff  1852 Oct  2 21:01 block.js
-rw-r--r--   1 kumavis  staff   386 Mar  5  2016 block.md
-rw-r--r--   1 kumavis  staff  4404 Oct 25 08:34 friends.js
-rw-r--r--   1 kumavis  staff  1829 Mar  5  2016 friends.md
drwxr-xr-x   5 kumavis  staff   170 Nov 16 14:14 gossip
-rw-r--r--   1 kumavis  staff  1459 Oct 25 07:44 gossip.md
-rw-r--r--   1 kumavis  staff  7093 Oct 25 07:44 invite.js
-rw-r--r--   1 kumavis  staff  1266 Oct 25 07:44 invite.md
-rw-r--r--   1 kumavis  staff   916 Oct 25 07:44 local.js
-rw-r--r--   1 kumavis  staff  2193 Oct 25 07:44 logging.js
-rw-r--r--   1 kumavis  staff   382 Oct 25 07:44 master.js
-rw-r--r--   1 kumavis  staff  8257 Oct 25 08:34 plugins.js
-rw-r--r--   1 kumavis  staff  1136 Oct 25 07:44 plugins.md
-rw-r--r--   1 kumavis  staff   887 Mar  5  2016 private.js
-rw-r--r--   1 kumavis  staff   626 Mar  5  2016 private.md
-rw-r--r--   1 kumavis  staff  6333 Oct 25 07:44 replicate.js
-rw-r--r--   1 kumavis  staff   327 Oct 25 07:44 replicate.md
```

**Comment by ahdinosaur** [comment]
hey. i'm closing this as stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).

if it's still a problem, open again!
