### ISSUE TITLE
TypeError: id.slice is not a function

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/patchwork#439]
just started happening:

```
TypeError: id.slice is not a function
    at About (/home/dinosaur/repos/ssbc/patchwork/node_modules/patchcore/about/obs.js:127:65)
    at get (/home/dinosaur/repos/ssbc/patchwork/node_modules/patchcore/about/obs.js:65:19)
    at Object.name (/home/dinosaur/repos/ssbc/patchwork/node_modules/patchcore/about/obs.js:33:21)
    at Object.name (/home/dinosaur/repos/ssbc/patchwork/node_modules/depject/apply.js:15:30)
    at Object.person (/home/dinosaur/repos/ssbc/patchwork/modules/profile/html/person.js:19:26)
    at Object.person (/home/dinosaur/repos/ssbc/patchwork/node_modules/depject/apply.js:15:30)
    at Object.manyPeople (/home/dinosaur/repos/ssbc/patchwork/modules/profile/html/manyPeople.js:39:33)
    at Object.manyPeople (/home/dinosaur/repos/ssbc/patchwork/node_modules/depject/apply.js:15:30)
    at renderItem (/home/dinosaur/repos/ssbc/patchwork/modules/feed/html/rollup.js:216:78)
    at add (/home/dinosaur/repos/ssbc/patchwork/node_modules/pull-scroll/index.js:42:15)
```

**Comment by mmckegg** [comment]
yep, tis miserable 😢 

Will push out a release soon!

**Comment by mmckegg** [comment]
@ahdinosaur we should track down what message is responsible and who's "fault" it was! Just for interest's sake 😼

**Comment by clehner** [comment]
> @ahdinosaur we should track down what message is responsible and who's "fault" it was! Just for interest's sake * 

maybe this:

{
  "key": "%n+SBv/eEvoyPLcaVhPp228JcWEmzTNr0KTZcgrh4Q7U=.sha256",
  "value": {
    "previous": "%uADMhLQkz1L7a8JKqf5xwRfEWGASbRip8vxEwPjaVAI=.sha256",
    "author": "@U5GvOKP/YUza9k53DSXxT0mk3PIrnyAmessvNfZl5E0=.ed25519",
    "sequence": "182",
    "timestamp": 1489718720580,
    "hash": "sha256",
    "content": {
      "type": "contact",
      "contact": {
        "isTrusted": true
      },
      "following": true
    },
    "signature": "0K7RqgLdGVHsXAjs2ydsFoAU1dPj5SETg65ZcIpcw9bKWe6O0/ISwZCu7tZqGuVLDbgPkkI+5FWo1fy4HfNUAQ==.sig.ed25519"
  }
}

app should handle every case, of course

**Comment by mmckegg** [comment]
Are any other ssb clients freaking out about this? Or is it just patchwork-next?

**Comment by clehner** [comment]
patchfoo rendered "... follows [object Object]". don't know about patchwork-classic

**Comment by ahdinosaur** [comment]
originated from `picknmix`, @mixmix accidentally published an event as a message, which is where [`isTrusted`](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) comes from.

brings up all the more reason for stronger type checking before publishing and filtering bad data from queries.

**Comment by mmckegg** [comment]
@ahdinosaur or maybe some shared vocab in patchcore. `contact.sync.follow` etc

@clehner I think patchwork-classic actually handled filtering bad data quite well. Gonna boot it up and see.

**Comment by mmckegg** [comment]
Yep, classic is fine!

**Comment by ahdinosaur** [comment]
yeah, i think classic used [`ssb-msg-schemas`](https://github.com/ssbc/ssb-msg-schemas). i'm keen to reboot something like this, so we can add type checking as we wish.

**Comment by dominictarr** [comment]
it's better to address this defensively, the renderer should always be able to validate and not display invalid things. (or something sensible) we fundamentially can't stop anyone posting invalid messages, apps just have to take it on the chin.

**Comment by mixmix** [comment]
Agree, i want a strainer over the stuff coming through my patchcore pulls
and obs
