### ISSUE TITLE
undefined symbol, non starter

### ISSUE THREAD

**Issue by NHQ** [ssbc/patchwork#50]
I upgraded node to latest@4.2.1 (no version manager) and still get this error.  I was able to get past it once, but on restart it came back, and since then can't defeat the bug.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /home/johnny/.npm/lib/node_modules/ssb-patchwork/node_modules/ssb-keys/node_modules/chloride/build/Release/sodium.node: undefined symbol: _ZN2v87Context10GetCurrentEv
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/johnny/.npm/lib/node_modules/ssb-patchwork/node_modules/ssb-keys/node_modules/chloride/lib/sodium.js:16:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

**Comment by dominictarr** [comment]
This happens when you have the wrong version of electron, i think.
How did you run it? if you cloned it, use `./bin.js` and that should use the locally installed, correct version.

One person had a weird error when using `sudo` with `npm install -g`. if that is the case try cloning, and then installing locally. If that still fails, can you post your install output?

**Comment by NHQ** [comment]
Does not the npm install download electron?

**Comment by dominictarr** [comment]
you got it working, what did you do?

**Comment by NHQ** [comment]
I cloned.

**Comment by clehner** [comment]
This is the same as I had in #14
