### ISSUE TITLE
Cannot read property delete of undefined

### ISSUE THREAD

**Issue by ralphtheninja** [ssbc/patchwork#503]
I get a gazillion messages of the type:

```
TypeError: Cannot read property 'delete' of undefined
    at onSync (/home/lms/src/ssbc/patchwork/node_modules/scuttlebot/plugins/replicate.js:268:42)
    at broadcastSync (/home/lms/src/ssbc/patchwork/node_modules/scuttlebot/plugins/replicate.js:359:17)
TypeError: Cannot read property 'delete' of undefined
    at onSync (/home/lms/src/ssbc/patchwork/node_modules/scuttlebot/plugins/replicate.js:268:42)
    at broadcastSync (/home/lms/src/ssbc/patchwork/node_modules/scuttlebot/plugins/replicate.js:359:17)
TypeError: Cannot read property 'delete' of undefined
    at onSync (/home/lms/src/ssbc/patchwork/node_modules/scuttlebot/plugins/replicate.js:268:42)
    at broadcastSync (/home/lms/src/ssbc/patchwork/node_modules/scuttlebot/plugins/replicate.js:359:17)
TypeError: Cannot read property 'delete' of undefined
    at onSync (/home/lms/src/ssbc/patchwork/node_modules/scuttlebot/plugins/replicate.js:268:42)
    at broadcastSync (/home/lms/src/ssbc/patchwork/node_modules/scuttlebot/plugins/replicate.js:359:17)
```

Any ideas?

**Comment by mmckegg** [comment]
Pretty sure this was fixed in https://github.com/ssbc/scuttlebot/pull/386

If not, will be fixed once https://github.com/ssbc/scuttlebot/pull/393 is merged.

**Comment by mmckegg** [comment]
The latest patchwork master has both of these patches rolled in already.
