### ISSUE TITLE
timestamp error

### ISSUE THREAD

**Issue by myf** [ssbc/patchwork#52]
both sbot and patchwork has this error occur when initialize
```
Uncaught Exception:
TypeError: Cannot read property 'timestamp' of undefined
    at /home/myf/.npm-packages/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/plugins/blobs.js:235:51
    at EventEmitter.<anonymous> (/home/myf/.npm-packages/lib/node_modules/ssb-patchwork/node_modules/muxrpc-validation/index.js:79:23)
    at EventEmitter.hooked [as get] (/home/myf/.npm-packages/lib/node_modules/ssb-patchwork/node_modules/hoox/index.js:10:15)
    at /home/myf/.npm-packages/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/plugins/blobs.js:233:20
    at /home/myf/.npm-packages/lib/node_modules/ssb-patchwork/node_modules/multiblob/index.js:77:15
    at continuation (/home/myf/.npm-packages/lib/node_modules/ssb-patchwork/node_modules/continuable-list/index.js:24:25)
    at /home/myf/.npm-packages/lib/node_modules/ssb-patchwork/node_modules/multiblob/index.js:56:9
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by dominictarr** [comment]
Can you install latest? I think we may have fixed this one
