### ISSUE TITLE
error upon uploading user image

### ISSUE THREAD

**Issue by mk30** [ssbc/patchwork#53]
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.

Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at Error (native)
    at draw (/home/marina/prefix/lib/node_modules/ssb-patchwork/ui/lib/com/image-uploader.js:50:9)
    at HTMLCanvasElement.onmouseup (/home/marina/prefix/lib/node_modules/ssb-patchwork/ui/lib/com/image-uploader.js:131:5)

This was an unhandled exception.

**Comment by pfraze** [comment]
Thanks, will look into it shortly

**Comment by pfraze** [comment]
Have you been able to find a way around the issue? We can probably find a workaround for you, if you're stuck.

**Comment by dominictarr** [comment]
This was caused by the image being a gif. it worked with a jpeg.
