### ISSUE TITLE
Not able to start on Debian/Jessie

### ISSUE THREAD

**Issue by soggypretzels** [ssbc/patchwork#545]
I built Patchwork from the git repo using the instructions (including installing the dependencies) but when I run "npm start" patchwork fails to load.

Should it matter if this is running on a headless virtual machine?

```
npm start

> ssb-patchwork@3.4.0 start /root/patchwork
> electron index.js

/root/patchwork/node_modules/electron/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```

Here is the npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ssb-patchwork@3.4.0~prestart: ssb-patchwork@3.4.0
6 silly lifecycle ssb-patchwork@3.4.0~prestart: no script for prestart, continuing
7 info lifecycle ssb-patchwork@3.4.0~start: ssb-patchwork@3.4.0
8 verbose lifecycle ssb-patchwork@3.4.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ssb-patchwork@3.4.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-
bin:/root/patchwork/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle ssb-patchwork@3.4.0~start: CWD: /root/patchwork
11 silly lifecycle ssb-patchwork@3.4.0~start: Args: [ '-c', 'electron index.js' ]
12 info lifecycle ssb-patchwork@3.4.0~start: Failed to exec start script
13 verbose stack Error: ssb-patchwork@3.4.0 start: `electron index.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:886:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid ssb-patchwork@3.4.0
15 verbose cwd /root/patchwork
16 error Linux 4.4.6-1-pve
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v6.10.3
19 error npm  v3.10.10
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error ssb-patchwork@3.4.0 start: `electron index.js`
24 error spawn ENOENT
25 error Failed at the ssb-patchwork@3.4.0 start script 'electron index.js'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the ssb-patchwork package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron index.js
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs ssb-patchwork
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls ssb-patchwork
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

**Comment by clehner** [comment]
try sudo apt-get install libxss1
and then re-run npm start.
if it still doesn't work, try posting output of this command:
ldd /root/patchwork/node_modules/electron/dist/electron | grep 'not found'

**Comment by soggypretzels** [comment]
Thanks for the help.

```
ldd /root/patchwork/node_modules/electron/dist/electron | grep 'not found'
        libgconf-2.so.4 => not found
        libnss3.so => not found
        libnssutil3.so => not found
        libsmime3.so => not found
        libnspr4.so => not found
        libasound.so.2 => not found
```

**Comment by clehner** [comment]
Ok, on my system those are provided by these packages:
libgconf-2-4 libnss3 libnspr4 libasound2

does it work if you apt-get install those?

**Comment by soggypretzels** [comment]
Now that those are installed when I do npm start I get a libGL error. The application does not halt, however, no window opens either.

```
npm start

> ssb-patchwork@3.4.0 start /root/patchwork
> electron index.js

libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/root/patchwork/node_modules/bindings/bindings.js:76:44)
```

**Comment by clehner** [comment]
ok, on my machine swrast_dri.so is provided by package libgl1-mesa-dri. 
that's probably for 3D acceleration, which electron might work without but 
it will probably speed up rendering.

as for the Module version mismatch, try running `npm run rebuild`

**Comment by soggypretzels** [comment]
I am no longer getting the libGL issue, but the Module version mismatch and symptoms remain.

**Comment by clehner** [comment]
hmm, that is a problem. if you are getting Module version mismatch after 
`npm run rebuild`, the only thing i can think to suggest is to install a 
nodejs version that uses ABI version 50 which is what electron is 
expecting. according to this page though [1], there doesn't seem to be one 
a node one for 50. so i'm not sure what to suggest :/
maybe someone else can help?

[1] https://github.com/lgeiger/node-abi

**Comment by soggypretzels** [comment]
Nope, you got it! node rebuild solved the issue. Thanks again for your help!

**Comment by clehner** [comment]
oh, cool! you're welcome.
