### ISSUE TITLE
error when opening Patchwork v3.4.0

### ISSUE THREAD

**Issue by mk30** [ssbc/patchwork#551]
i run lubuntu 14.04. i followed the install directions in the patchwork readme:

sudo apt-get install g++ m4 libtool automake # build tools
sudo apt-get install libxext-dev libxtst-dev libxkbfile-dev # spellchecker headers
$ git clone https://github.com/ssbc/patchwork
$ cd patchwork
$ npm install
$ npm start

when i did "npm start" i got the following error:

```
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/marina/dev/patchwork/node_modules/bindings/bindings.js:76:44)
```

**Comment by ahdinosaur** [comment]
hey @mk30, try `npm run rebuild` :sparkles: 

this will rebuild your `node_modules` to support the current `electron` version. it's _supposed_ to [run during `postinstall`](https://github.com/ssbc/patchwork/blob/2b26681719856323d66d06c4c0b35411b7cd7a37/package.json#L11), wonder what happened ¯\\\_(ツ)\_/¯

**Comment by mk30** [comment]
@ahdinosaur thanks - that worked!
