### ISSUE TITLE
another infinite load of death bug

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/patchwork#569]
this happened using latest `3.6.2`

```
TypeError: Cannot read property 'content' of undefined
    at rootFilter (/home/dinosaur/repos/ssbc/patchwork/modules/page/html/render/gatherings.js:30:37)
    at pull.filter (/home/dinosaur/repos/ssbc/patchwork/modules/feed/html/rollup.js:77:59)
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/pull-stream/throughs/filter.js:15:23
    at drain (/home/dinosaur/repos/ssbc/patchwork/node_modules/pull-paramap/index.js:19:11)
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/pull-paramap/index.js:45:13
    at api.sbot.async.get (/home/dinosaur/repos/ssbc/patchwork/modules/feed/html/rollup.js:207:11)
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/patchcore/sbot.js:108:31
    at Object._requests.(anonymous function) (/home/dinosaur/repos/ssbc/patchwork/node_modules/packet-stream/index.js:38:5)
    at PacketStream._onrequest (/home/dinosaur/repos/ssbc/patchwork/node_modules/packet-stream/index.js:151:26)
    at PacketStream.write (/home/dinosaur/repos/ssbc/patchwork/node_modules/packet-stream/index.js:134:41)
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/muxrpc/pull-weird.js:56:15
```

**Comment by ahdinosaur** [comment]
hm, close and re-open, now it works fine. :sweat_smile:

**Comment by mmckegg** [comment]
Oh I see what is causing it! It's when you try and render a message when the root hasn't downloaded yet! That's why it went away.

**Comment by mmckegg** [comment]
@ahdinosaur This is a bad issue, we should pull the latest release and do a new one.

**Comment by kylerschin** [comment]
Till the end of time!
