### ISSUE TITLE
non-breaking error thrown when adding blobs

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#580]
```
TypeError: cb is not a function
    at /Users/matt/Code/patchwork/node_modules/ssb-client/blobs.js:29:11
    at /Users/matt/Code/patchwork/node_modules/muxrpc/pull-weird.js:69:14
    at /Users/matt/Code/patchwork/node_modules/muxrpc/pull-weird.js:18:14
    at /Users/matt/Code/patchwork/node_modules/muxrpc/pull-weird.js:10:5
    at /Users/matt/Code/patchwork/node_modules/muxrpc/pull-weird.js:59:17
    at /Users/matt/Code/patchwork/node_modules/pull-stream/sinks/drain.js:20:24
    at /Users/matt/Code/patchwork/node_modules/pull-stream/sources/values.js:19:7
    at next (/Users/matt/Code/patchwork/node_modules/pull-stream/sinks/drain.js:16:11)
    at sink (/Users/matt/Code/patchwork/node_modules/pull-stream/sinks/drain.js:37:9)
    at sink (/Users/matt/Code/patchwork/node_modules/muxrpc/pull-weird.js:61:7)
```

**Comment by mmckegg** [comment]
@dominictarr could this be a problem with ssb-client?
