### ISSUE TITLE
error loading sodium bindings: No native build was found for runtime=electron abi=57 platform=linux arch=x64, falling back to javascript version

### ISSUE THREAD

**Issue by roberto68** [ssbc/patchwork#623]
I got this error: 
` error loading sodium bindings: The module '/home/roberto/bin/patchwork-source/node_modules/sodium-prebuilt/build/Release/sodium.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
falling back to javascript version.
error loading sodium bindings: No native build was found for runtime=electron abi=57 platform=linux arch=x64
falling back to javascript version.
error loading sodium bindings: No native build was found for runtime=electron abi=57 platform=linux arch=x64
falling back to javascript version.
Error: The module '/home/roberto/bin/patchwork-source/node_modules/leveldown/build/Release/leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/home/roberto/bin/patchwork-source/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/roberto/bin/patchwork-source/node_modules/leveldown/leveldown.js:4:46) 
`
I tried v7.4.0 and 6.0.0 but still the same. I did npm install sodium, npm rebuild sodium but didn't help.

**Comment by dominictarr** [comment]
what node version are you on?

**Comment by roberto68** [comment]
it is in the bottom of the post - I've tried 7.4.0 and 6 but result the same so it doesn't seem to be the case

**Comment by mmckegg** [comment]
Running `npm run rebuild` should fix this.

Closing this issue. Please reopen if you are still having problems!
