### ISSUE TITLE
error loading sodium bindings: Cannot find module 'sodium-prebuilt/build/Release/sodium'

### ISSUE THREAD

**Issue by roberto68** [ssbc/patchwork#625]
`
npm start

> ssb-patchwork@3.6.6 start /home/roberto/bin/patchwork-source
> electron index.js

error loading sodium bindings: Cannot find module 'sodium-prebuilt/build/Release/sodium'
falling back to javascript version.
Error: Cannot find module 'bindings'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/roberto/.nvm/versions/node/v8.0.0/lib/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/roberto/bin/patchwork-source/node_modules/leveldown/leveldown.js:4:27)
    at Object.<anonymous> (/home/roberto/bin/patchwork-source/node_modules/leveldown/leveldown.js:109:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
^C
`
I need to remove sodium prebuilt cause I was getting - different version error, I did npm rebuild and npm install too and this is what I get. I'm on node 8.0.0. At 7.4.0 I get different version error at 6.0.0 electron not found...

**Comment by itsrachelfish** [comment]
I had a similar issue with leveldown which may be related to this:

```
rachel@rachel76:~/Projects/Misc/patchwork$ npm start

> ssb-patchwork@3.7.1 start ~/Projects/Misc/patchwork
> electron index.js

error loading sodium bindings: No native build was found for runtime=electron abi=57 platform=linux arch=x64
falling back to javascript version.
error loading sodium bindings: No native build was found for runtime=electron abi=57 platform=linux arch=x64
falling back to javascript version.
Error: The module '~/Projects/Misc/patchwork/node_modules/leveldown/build/Release/leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (~/Projects/Misc/patchwork/node_modules/bindings/bindings.js:76:44)
at Object.<anonymous> (~/Projects/Misc/patchwork/node_modules/leveldown/leveldown.js:4:46)
```
I solved this issue by doing the following:

```
cd node_modules/leveldown
node-gyp rebuild
```

**Comment by roberto68** [comment]
after new update it is OK
