### ISSUE TITLE
Error sending long private message

### ISSUE THREAD

**Issue by gmarcos87** [ssbc/patchwork#640]
When I try to send a very long private message, the system gets mixed up. Looking at the log encounter this exception without handle:

```
base.html:19 error loading sodium bindings: No native build was found for runtime=electron abi=57 platform=linux arch=x64
console.error @ base.html:19
base.html:19 falling back to javascript version.
console.error @ base.html:19
base.html:19 Objectmessage: "encoded message must not be larger than 8192 bytes"name: "Error"stack: "Error: encoded message must not be larger than 8192 bytes↵    at Object.exports.isInvalidShape (/home/ubuntu/ssbc/patchwork-origin/node_modules/ssb-feed/util.js:117:12)↵    at add (/home/ubuntu/ssbc/patchwork-origin/node_modules/ssb-feed/validator.js:101:20)↵    at next (/home/ubuntu/ssbc/patchwork-origin/node_modules/secure-scuttlebutt/index.js:103:7)↵    at Object.db.add (/home/ubuntu/ssbc/patchwork-origin/node_modules/secure-scuttlebutt/index.js:100:24)↵    at apply (/home/ubuntu/ssbc/patchwork-origin/node_modules/muxrpc-validation/index.js:173:15)↵    at Object.<anonymous> (/home/ubuntu/ssbc/patchwork-origin/node_modules/muxrpc-validation/index.js:82:14)↵    at Object.hooked (/home/ubuntu/ssbc/patchwork-origin/node_modules/hoox/index.js:10:15)↵    at Object.localCall (/home/ubuntu/ssbc/patchwork-origin/node_modules/muxrpc/local-api.js:31:31)↵    at Object.<anonymous> (/home/ubuntu/ssbc/patchwork-origin/node_modules/muxrpc/local-api.js:37:22)↵    at Object.request (/home/ubuntu/ssbc/patchwork-origin/node_modules/muxrpc/stream.js:46:17)"__proto__: Object
console.error @ base.html:19
base.html:19 Error: encoded message must not be larger than 8192 bytes
    at Object.exports.isInvalidShape (/home/ubuntu/ssbc/patchwork-origin/node_modules/ssb-feed/util.js:117:12)
    at add (/home/ubuntu/ssbc/patchwork-origin/node_modules/ssb-feed/validator.js:101:20)
    at next (/home/ubuntu/ssbc/patchwork-origin/node_modules/secure-scuttlebutt/index.js:103:7)
    at Object.db.add (/home/ubuntu/ssbc/patchwork-origin/node_modules/secure-scuttlebutt/index.js:100:24)
    at apply (/home/ubuntu/ssbc/patchwork-origin/node_modules/muxrpc-validation/index.js:173:15)
    at Object.<anonymous> (/home/ubuntu/ssbc/patchwork-origin/node_modules/muxrpc-validation/index.js:82:14)
    at Object.hooked (/home/ubuntu/ssbc/patchwork-origin/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/ubuntu/ssbc/patchwork-origin/node_modules/muxrpc/local-api.js:31:31)
    at Object.<anonymous> (/home/ubuntu/ssbc/patchwork-origin/node_modules/muxrpc/local-api.js:37:22)
    at Object.request (/home/ubuntu/ssbc/patchwork-origin/node_modules/muxrpc/stream.js:46:17)
console.error @ base.html:19
```

It may be necessary to display an error message or calculate the total length before sending and locking the button until the user does not cut the message.

Another way is to send the fragmented message into multiple parts of the maximum possible size.

**Comment by ahdinosaur** [comment]
related to https://github.com/ssbc/patchwork/issues/456

**Comment by mmckegg** [comment]
@gmarcos87 the error now appears as a dialog in the interface.

I'm going to close this issue in favour of continuing in #456
