### ISSUE TITLE
npm install broken

### ISSUE THREAD

**Issue by gubatron** [ssbc/patchwork#665]
Tried your installation instructions.
Cloned repo, tried `npm install`

```
> typechecker@2.0.8 preinstall /Users/gubatron/src/patchwork/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js

npm ERR! Cannot read property 'pause' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gubatron/.npm/_logs/2017-11-03T16_35_38_771Z-debug.log
```

Here's the log:
```
14480 verbose stack     at dequeue (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:201:12)
14480 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:131:7)
14480 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
14481 verbose cwd /Users/gubatron/src/patchwork
14482 verbose Darwin 16.7.0
14483 verbose argv "/usr/local/Cellar/node/8.8.1/bin/node" "/usr/local/bin/npm" "install"
14484 verbose node v8.8.1
14485 verbose npm  v5.4.2
14486 error Cannot read property 'pause' of undefined
14487 verbose exit [ 1, true ]
```

hope that helps, heard about this at DevCon3, got no time to get to the bottom of it and send a patch. Good to see projects like these happening.

**Comment by drandreaskrueger** [comment]
### npm ERR! code ELIFECYCLE

yes, same here, and also heard about it at DevCon, however via the livestream [:-)](https://github.com/drandreaskrueger/devcon3)

My error messages look different:

```
sudo apt-get install g++ m4 libtool automake libgconf-2-4   # build tools
sudo apt-get install libxext-dev libxtst-dev libxkbfile-dev # spellchecker headers

npm install

> typechecker@2.0.8 preinstall ~/Documents/Code/ssbc/patchwork/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall ~/Documents/Code/ssbc/patchwork/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js


> @paulcbetts/spellchecker@4.0.6 install ~/Documents/Code/ssbc/patchwork/node_modules/@paulcbetts/spellchecker
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! @paulcbetts/spellchecker@4.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the @paulcbetts/spellchecker@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2017-11-04T03_07_26_901Z-debug.log


```


this you want to know:

```
npm --version; node --version; uname -a
5.5.1
v8.9.0
Linux ... 4.12.0-14.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 4.12-9 (2017-09-26) x86_64 GNU/Linux
```

**Comment by gubatron** [comment]
(same here, through the livestream!)

**Comment by mmckegg** [comment]
@gubatron 

Looks like you've hit an npm bug. What version of npm are you running? 

Found this: https://github.com/npm/npm/issues/18520

> 5.5.0 and 5.5.1 have the fixes for this issue. Thank you!

---

@drandreaskrueger 

The line in that error log that matters is:

```
sh: 1: node-gyp: Permission denied
```

Found [this](https://stackoverflow.com/questions/14313432/nodejs-node-gyp-rebuild-access-is-denied#17022354) but not sure if it will be helpful.

**Comment by gubatron** [comment]
```Angels-MacBook-Pro:patchwork gubatron$ npm --version
5.5.1
```

pulled again, today Nov 9 2017
```
Angels-MacBook-Pro:patchwork gubatron$ git pull origin master
remote: Counting objects: 96, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 96 (delta 58), reused 73 (delta 51), pack-reused 15
Unpacking objects: 100% (96/96), done.
From https://github.com/ssbc/patchwork
 * branch              master     -> FETCH_HEAD
   8b3e0bbd..695f6649  master     -> origin/master
Updating 8b3e0bbd..695f6649
Fast-forward
 lib/context-menu-and-spellcheck.js   |  2 +-
 lib/expander-hook.js                 |  2 +-
 lib/sustained.js                     |  5 +++--
 locales/en.json                      |  3 ++-
 modules/app/link-preview.js          | 20 ++++++++++++++++++--
 modules/feed/html/rollup.js          | 26 +++++++++++++++++++-------
 modules/message/html/missing.js      | 23 ++++++++++++++++++++---
 modules/page/html/render/mentions.js |  1 +
 modules/page/html/render/message.js  |  8 +++++++-
 modules/page/html/render/profile.js  |  1 +
 package.json                         |  8 ++++----
 plugs/message/html/layout/default.js | 19 ++++++++++++++++---
 styles/dark/message.mcss             |  6 ++++++
 styles/light/message.mcss            | 10 ++++++++--
 14 files changed, 107 insertions(+), 27 deletions(-)
```

```Angels-MacBook-Pro:patchwork gubatron$ npm install

> sodium-native@2.0.0 install /Users/gubatron/src/patchwork/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"

sh: node-gyp-build: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! sodium-native@2.0.0 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sodium-native@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gubatron/.npm/_logs/2017-11-09T07_16_01_048Z-debug.log
```

```Angels-MacBook-Pro:patchwork gubatron$ cat /Users/gubatron/.npm/_logs/2017-11-09T07_16_01_048Z-debug.log
...
1376 verbose lifecycle sodium-native@2.0.0~install: CWD: /Users/gubatron/src/patchwork/node_modules/sodium-native
1377 silly lifecycle sodium-native@2.0.0~install: Args: [ '-c',
1377 silly lifecycle   'node-gyp-build "node preinstall.js" "node postinstall.js"' ]
1378 info lifecycle sodium-native@2.0.0~install: Failed to exec install script
1379 verbose unlock done using /Users/gubatron/.npm/_locks/staging-c245074fbe5c9c71.lock for /Users/gubatron/src/patchwork/node_modules/.staging
1380 verbose stack Error: sodium-native@2.0.0 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
1380 verbose stack spawn ENOENT
1380 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
1380 verbose stack     at emitTwo (events.js:126:13)
1380 verbose stack     at ChildProcess.emit (events.js:214:7)
1380 verbose stack     at maybeClose (internal/child_process.js:925:16)
1380 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1381 verbose pkgid sodium-native@2.0.0
1382 verbose cwd /Users/gubatron/src/patchwork
1383 verbose Darwin 16.7.0
1384 verbose argv "/usr/local/Cellar/node/8.9.0/bin/node" "/usr/local/bin/npm" "install"
1385 verbose node v8.9.0
1386 verbose npm  v5.5.1
1387 error file sh
1388 error code ELIFECYCLE
1389 error errno ENOENT
1390 error syscall spawn
1391 error sodium-native@2.0.0 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
1391 error spawn ENOENT
1392 error Failed at the sodium-native@2.0.0 install script.
1392 error This is probably not a problem with npm. There is likely additional logging output above.
1393 verbose exit [ 1, true ]
```

**Comment by gubatron** [comment]
`Angels-MacBook-Pro:patchwork gubatron$ npm install node-gyp-build`

```
> sodium-native@2.0.0 install /Users/gubatron/src/patchwork/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"
npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-gyp-build@3.2.2
added 1 package, removed 310 packages and updated 1 package in 5.958s
```

now let's try again:
`Angels-MacBook-Pro:patchwork gubatron$ npm install`

Progress!
```
> ssb-patchwork@3.8.0 postinstall /Users/gubatron/src/patchwork
> npm run rebuild


> ssb-patchwork@3.8.0 rebuild /Users/gubatron/src/patchwork
> cross-script npm rebuild --runtime=electron "--target=$(electron -v)" "--abi=$(electron --abi)" --disturl=https://atom.io/download/atom-shell

sh: electron: command not found
sh: electron: command not found
sh: cross-script: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ssb-patchwork@3.8.0 rebuild: `cross-script npm rebuild --runtime=electron "--target=$(electron -v)" "--abi=$(electron --abi)" --disturl=https://atom.io/download/atom-shell`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ssb-patchwork@3.8.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gubatron/.npm/_logs/2017-11-09T07_21_47_796Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssb-patchwork@3.8.0 postinstall: `npm run rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssb-patchwork@3.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gubatron/.npm/_logs/2017-11-09T07_21_47_851Z-debug.log
```

I see `node-gyp-build` in your `package.json` file, wonder why it didn't try to install it, perhaps it should be moved to another section.

Now I guess it's complaining about `electron`

tried the `npm rebuild` it suggested...

then again `npm install`

gave this error along the way:
```
> fsevents@1.1.2 install /Users/gubatron/src/patchwork/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-electron-v1.8-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and electron@v1.8.1 (electron-v1.8 ABI) (falling back to source compile with node-gyp) 
```

but it seems like it finished this time

```
...
fstream-ignore@1.0.5 /Users/gubatron/src/patchwork/node_modules/fsevents/node_modules/fstream-ignore
uid-number@0.0.6 /Users/gubatron/src/patchwork/node_modules/fsevents/node_modules/uid-number
bcrypt-pbkdf@1.0.1 /Users/gubatron/src/patchwork/node_modules/fsevents/node_modules/bcrypt-pbkdf
tweetnacl@0.14.5 /Users/gubatron/src/patchwork/node_modules/fsevents/node_modules/tweetnacl
ecc-jsbn@0.1.1 /Users/gubatron/src/patchwork/node_modules/fsevents/node_modules/ecc-jsbn
jsbn@0.1.1 /Users/gubatron/src/patchwork/node_modules/fsevents/node_modules/jsbn
jodid25519@1.0.2 /Users/gubatron/src/patchwork/node_modules/fsevents/node_modules/jodid25519
up to date in 48.108s
Angels-MacBook-Pro:patchwork gubatron$
```

`npm start`

It seems like it twerked!
![screen shot 2017-11-09 at 12 27 08 am](https://user-images.githubusercontent.com/163977/32593333-c437ee78-c4e4-11e7-9568-7fd5ac7d9716.png)

Hope this helps somebody else.

**Comment by drandreaskrueger** [comment]
Please add this to your how to install instructions:

    node install -g node-gyp

now it worked. The electron  `node install.js` part took ages without any feedback, but eventually it finished.

Whole procedure:

```
git reset --hard
git pull origin master

sudo npm uninstall -g node-gyp
sudo npm install -g node-gyp

rm -rf node_modules
npm install
```

Hooray, it works.

Thanks a lot!

**Comment by mmckegg** [comment]
I thought that `node-gyp` was included with node. Maybe it was removed? 

I suppose we could just add it as a `devDependency` in patchwork and avoid all of this.

**Comment by mmckegg** [comment]
I'm gonna go ahead and close this! Anyone is welcome to reopen this if node-gyp continues to be a problem. Hopefully fixed now.
