### ISSUE TITLE
Doesn't work on Trisquel 7

### ISSUE THREAD

**Issue by tmakarios** [ssbc/patchwork#666]
I tried running the 3.7.1 AppImage on Trisquel 7 (based on Ubuntu Trusty), but all I end up with is a blank grey window.  When I start the AppImage from the command line, I get this error:
```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.NZjUM2)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_yAM03c/usr/bin/resources/app.asar/node_modules/@paulcbetts/spellchecker/lib/spellchecker.js:3:16)
    at Object.<anonymous> (/tmp/.mount_yAM03c/usr/bin/resources/app.asar/node_modules/@paulcbetts/spellchecker/lib/spellchecker.js:116:3)
```
I _think_ the version of libstdc++6 I have installed is 4.8.4.

**Comment by mmckegg** [comment]
I think this is the same issue as https://github.com/ssbc/patchwork/issues/612 which @ahdinosaur is going to solve by setting up a better build environment at some point.

**Comment by tmakarios** [comment]
I think you're right; sorry, I didn't recognize that as a duplicate when skimming down the list of issue titles.  I can't figure out how to close this issue as a duplicate; is that something only privileged people can do?

**Comment by mmckegg** [comment]
Yeah, I think so. I'll mark it for you 😄
