### ISSUE TITLE
rework: some times feed disappears and won't come back

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#68]
Sometimes the views (via lefthand menu) get into a weird state and won't show anything.
It looks like it's started loading but something happened and it just got stuck or forgot.
Restarting patchwork fixes it.

I did see this error in my console, but I don't really know if it's related.
```
TypeError: Cannot read property 'height' of undefined
    at Card.componentDidMount (/home/dominic/c/ssb/patchwork/ui/com/msg-list/card.jsx:88:31)
    at CallbackQueue.assign.notifyAll (/home/dominic/c/ssb/patchwork/node_modules/react/lib/CallbackQueue.js:65:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/home/dominic/c/ssb/patchwork/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (/home/dominic/c/ssb/patchwork/node_modules/react/lib/Transaction.js:202:25)
    at ReactReconcileTransaction.Mixin.perform (/home/dominic/c/ssb/patchwork/node_modules/react/lib/Transaction.js:149:16)
    at ReactUpdatesFlushTransaction.Mixin.perform (/home/dominic/c/ssb/patchwork/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.assign.perform (/home/dominic/c/ssb/patchwork/node_modules/react/lib/ReactUpdates.js:86:38)
    at Object.flushBatchedUpdates (/home/dominic/c/ssb/patchwork/node_modules/react/lib/ReactUpdates.js:147:19)
    at Object.wrapper [as flushBatchedUpdates] (/home/dominic/c/ssb/patchwork/node_modules/react/lib/ReactPerf.js:66:21)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/home/dominic/c/ssb/patchwork/node_modules/react/lib/Transaction.js:202:25)
```

Since using the new patchwork earlier today this has happened twice.
I'll post if this happens again and if I get any clues as to what this is.

**Comment by pfraze** [comment]
Yeah thanks, I saw this too. Got it on my list.

**Comment by pfraze** [comment]
should be fixed with https://github.com/ssbc/patchwork/commit/86452344896ffa0c41f1d908e06b08b1ac0e4b22
