### ISSUE TITLE
Light grey screen of nothing on 3.8.1

### ISSUE THREAD

**Issue by mischa-s** [ssbc/patchwork#683]
I tried using 3.8.1 (via pulling master) this morning and just got an empty electron window with a scuttle crab top left. Basic effort at debugging was: rm -rf node modules ; npm i 
I also tried letting it sit for +/- 30 minutes with no change

Errors in terminal consistently include: 
```
Error: Cannot find module 'emojilib' 

TypeError: normalizeChannel is not a function

error: 'Error: connect ECONNREFUSED 185.8.164.44:8008\n    at Object.exports._errnoException 
(util.js:1024:11)\n    at exports._exceptionWithHostPort (util.js:1047:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)' } 

error: 'Error: hello not accepted\n    at abort 
```

Any thoughts @mmckegg ?

**Comment by mischa-s** [comment]
I think I ended up down some weird rabbit hole that wont be simple to debug so I just cloned and then nuked my identity and am starting with a fresh install and got to experience the super lovely and easy experience on boarding!
