### ISSUE TITLE
Yet another infinite scuttling in Patchwork-3.8.6-linux-x86_64.AppImage

### ISSUE THREAD

**Issue by bhaugen** [ssbc/patchwork#702]
On Ubuntu 16.04. Stuck on this, while viewing full thread::
```
Error: thread has duplicate message:%prnNmhf75p0wYdgk5e3sr/QhOgFy/ALsI8JHcCdH40U=.sha256
    at messages (/tmp/.mount_PatchwCcDaOw/app/resources/app.asar/node_modules/ssb-sort/index.js:21:13)
    at Function.heads (/tmp/.mount_PatchwCcDaOw/app/resources/app.asar/node_modules/ssb-sort/index.js:59:16)
    at Object.result.lastId.computed (/tmp/.mount_PatchwCcDaOw/app/resources/app.asar/node_modules/patchcore/feed/obs/thread.js:50:29)
    at ProtoComputed.update (/tmp/.mount_PatchwCcDaOw/app/resources/app.asar/node_modules/mutant/computed.js:134:42)
    at ProtoComputed.listen (/tmp/.mount_PatchwCcDaOw/app/resources/app.asar/node_modules/mutant/computed.js:91:17)
    at ProtoComputed.getValue (/tmp/.mount_PatchwCcDaOw/app/resources/app.asar/node_modules/mutant/computed.js:196:12)
    at ProtoComputed.MutantComputed (/tmp/.mount_PatchwCcDaOw/app/resources/app.asar/node_modules/mutant/computed.js:55:19)
    at resolve (/tmp/.mount_PatchwCcDaOw/app/resources/app.asar/node_modules/mutant/resolve.js:4:41)
    at update (/tmp/.mount_PatchwCcDaOw/app/resources/app.asar/node_modules/mutant/proxy.js:55:20)
    at Object.updateAndBroadcast (/tmp/.mount_PatchwCcDaOw/app/resources/app.asar/node_modules/mutant/lib/lazy-watcher.js:54:18)
```

**Comment by mmckegg** [comment]
@dominictarr Do you have any ideas how this could happen? Looks like a message is in the log twice?

I have seen this before, and I recall that deleting the indexes was not enough, and I had to completely redownload the log to fix.

@bhaugen Can you try deleting every other file **except for offset.log** inside of `~/.ssb/flume`, and see if that fixes it? If it doesn't, it might be helpful to (somehow) send the offset.log file to @dominictarr for debugging! (and then do a full resync)

**Comment by bhaugen** [comment]
@mmckegg the problem has not recurred. I tried this morning to reproduce it so I could try your suggested fix, but failed to trigger that error again. If and when it happens again, I will try that deletion and see if it solves the problem, and report back here. (Without a recurrence, we won't know if the fix works.)

**Comment by dominictarr** [comment]
if it's in the not in the log it must be in the index!

**Comment by bhaugen** [comment]
I have not seen a recurrence.

**Comment by mmckegg** [comment]
Closing this for now, feel free to reopen if this turns up again!

**Comment by voppe** [comment]
Turned up for me. Similar to @christianbundy, I probably ran two ssb instances since I am trying out various ssb applications (Patchwork, Patchfoo) and I am running them randomly with the shared ~/.ssb data, so something got corrupt.

```
Error: thread has duplicate message:%Z3SbXlxYiiCHSnRSOdmNlE46jVD/YagVW4FJbvOHyIc=.sha256
    at messages (/opt/ssb-patchwork/node_modules/ssb-sort/index.js:21:13)
    at Function.heads (/opt/ssb-patchwork/node_modules/ssb-sort/index.js:59:16)
    at Object.result.lastId.computed (/opt/ssb-patchwork/node_modules/patchcore/feed/obs/thread.js:75:29)
    at ProtoComputed.update (/opt/ssb-patchwork/node_modules/mutant/computed.js:134:42)
    at ProtoComputed.listen (/opt/ssb-patchwork/node_modules/mutant/computed.js:91:17)
    at ProtoComputed.getValue (/opt/ssb-patchwork/node_modules/mutant/computed.js:196:12)
    at ProtoComputed.MutantComputed (/opt/ssb-patchwork/node_modules/mutant/computed.js:55:19)
    at resolve (/opt/ssb-patchwork/node_modules/mutant/resolve.js:4:41)
    at update (/opt/ssb-patchwork/node_modules/mutant/proxy.js:55:20)
    at Object.updateAndBroadcast (/opt/ssb-patchwork/node_modules/mutant/lib/lazy-watcher.js:54:18)
```

**Comment by mmckegg** [comment]
As far as I can tell, this is a view only bug. The database itself is fine.

I think there might be an issue where patchwork gets subscribed to the same thread more than once (possibly because of the multiple instances) and then doubles up on messages. This could be hacked around be adding a check for double ups here: https://github.com/ssbc/patchwork/blob/a9fe8868dd71da9e2f16834cdf26233521d56798/overrides/patchcore/backlinks/obs.js#L70

**Comment by bhaugen** [comment]
Tried again, more patiently, and it finally finished. Shut down, started up again, pretty quick that time..

So you could ignore my comment above, or delete it. I didnt delete it because I thought it might have some useful info.

**Comment by voppe** [comment]
Got him. Took me way longer than I care to admit but this guy is the responsible.

https://github.com/ssbc/patchwork/blob/77570f8a228dbe5f1d398a92623d4c25675654ec/modules/page/html/render/message.js#L97

Commenting out the lines gets it unstuck.
