### ISSUE TITLE
Uncaught Exception when hitting 'quit'

### ISSUE THREAD

**Issue by oren** [ssbc/patchwork#73]
I get this error when I click on 'quit':

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Menu.sendActionToFirstResponder is not a function
    at MenuItem.click (/home/oren/.npm/lib/node_modules/ssb-patchwork/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/api/lib/menu-item.js:60:25)
    at Function.delegate.executeCommand (/home/oren/.npm/lib/node_modules/ssb-patchwork/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/api/lib/menu.js:127:69)
```

**Comment by altano** [comment]
I'm hitting this as well on Windows.  This reproduces the issue: https://github.com/hokein/electron-sample-apps/tree/master/tray

**Comment by mmckegg** [comment]
No updates for a while. Going to assume this is okay now! Closing.
