### ISSUE TITLE
Error: could not connect to sbot

### ISSUE THREAD

**Issue by AljoschaMeyer** [ssbc/patchwork#867]
Hey, my patchwork fails to connect to sbot, it just goes into an infinite loading animation upon startup.

Error log:

```
> ssb-patchwork@3.11.0 start /home/aljoscha/inactive-projects/patchwork
> electron index.js

error loading sodium bindings: The module '/home/aljoscha/inactive-projects/patchwork/node_modules/sodium-native/build/Release/sodium.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
falling back to javascript version.
{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3 },
  connections: { incoming: { net: [Array] }, outgoing: { net: [Array] } },
  path: '/home/aljoscha/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  plugins: 
   { 'ssb-links': true,
     'ssb-query': true,
     'ssb-ws': true,
     'ssb-fulltext': true },
  _: [],
  configs: [ '/home/aljoscha/.ssb/config' ],
  config: '/home/aljoscha/.ssb/config' }
error loading sodium bindings: The module '/home/aljoscha/inactive-projects/patchwork/node_modules/sodium-native/build/Release/sodium.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
falling back to javascript version.
ssb-friends: createFriendStream legacy api used
error loading sodium bindings: No native build was found for runtime=node abi=64 platform=linux arch=x64
falling back to javascript version.
error loading sodium bindings: The module '/home/aljoscha/inactive-projects/patchwork/node_modules/sodium-native/build/Release/sodium.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
falling back to javascript version.
/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/git-ssb-web/server.js:19
  if (err) throw err
           ^

Error: could not connect to sbot
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/ssb-client/index.js:96:23
    at next (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/multiserver/compose.js:24:14)
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/multiserver/compose.js:34:9
    at _cb (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/multiserver/plugins/shs.js:28:20)
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/secret-handshake/protocol.js:115:22
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-handshake/index.js:10:5
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-handshake/index.js:23:13
    at callback (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-pushable/index.js:82:7)
    at drain (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-pushable/index.js:69:39)
  Error: hello not accepted
    at abort (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/secret-handshake/protocol.js:36:45)
    at Object.cb (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/secret-handshake/protocol.js:50:26)
    at drain (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:42:23)
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:59:18
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:20:7
    at drain (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/stream-to-pull-stream/index.js:162:5)
    at Socket.emit (events.js:187:15)
    at TCP._handle.close (net.js:606:12)
```

The keys in `~/.ssb/secret` should be fine, because patchbay still works. Patchwork was installed via `git clone` followed by `npm install`, the newest commit was https://github.com/ssbc/patchwork/commit/deb0387d3f975972fb90310caeb075cb43060770 (I'm hesitant to `git pull` again, you wrote that the master branch is all over the place right now. Starting it with `npm start`.

I have no idea what might have caused this, but patchwork now consistently refuses to start. It worked before, I didn't install anything, in between didn't even restart the computer. It just decided to break =/

- `node --version`: `v10.11.0`
- `electron --version`: `v2.0.9`
- `uname -a`: `Linux aljoscha-laptop 4.18.10-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 26 09:48:22 UTC 2018 x86_64 GNU/Linux`

**Comment by christianbundy** [comment]
Not at home right now so I can't debug well, but could you run `npm run rebuild` and see if `npm start` still gives those Node ABI errors?

**Comment by AljoschaMeyer** [comment]
@christianbundy Nope, didn't help. Btw I get the same error when using your aur package `ssb-patchwork 3.11.0-1`.

**Comment by AljoschaMeyer** [comment]
Wait, rebuild did remove the ABI errors, but the problem persisted. New error log:

```
error loading sodium bindings: /opt/ssb-patchwork/node_modules/sodium-native/build/Release/sodium.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
falling back to javascript version.
{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3 },
  connections: { incoming: { net: [Array] }, outgoing: { net: [Array] } },
  path: '/home/aljoscha/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  plugins: 
   { 'ssb-links': true,
     'ssb-query': true,
     'ssb-ws': true,
     'ssb-fulltext': true },
  _: [],
  configs: [ '/home/aljoscha/.ssb/config' ],
  config: '/home/aljoscha/.ssb/config' }
error loading sodium bindings: /opt/ssb-patchwork/node_modules/sodium-native/build/Release/sodium.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
falling back to javascript version.
ssb-friends: createFriendStream legacy api used
error loading sodium bindings: No native build was found for runtime=node abi=64 platform=linux arch=x64
falling back to javascript version.
error loading sodium bindings: /opt/ssb-patchwork/node_modules/sodium-native/build/Release/sodium.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
falling back to javascript version.
/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/git-ssb-web/server.js:19
  if (err) throw err
           ^

Error: could not connect to sbot
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/ssb-client/index.js:96:23
    at next (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/multiserver/compose.js:24:14)
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/multiserver/compose.js:34:9
    at _cb (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/multiserver/plugins/shs.js:28:20)
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/secret-handshake/protocol.js:115:22
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-handshake/index.js:10:5
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-handshake/index.js:23:13
    at callback (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-pushable/index.js:82:7)
    at drain (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-pushable/index.js:69:39)
  Error: hello not accepted
    at abort (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/secret-handshake/protocol.js:36:45)
    at Object.cb (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/secret-handshake/protocol.js:50:26)
    at drain (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:42:23)
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:59:18
    at /home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:20:7
    at drain (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/aljoscha/.node_modules/lib/node_modules/git-ssb/node_modules/stream-to-pull-stream/index.js:162:5)
    at Socket.emit (events.js:187:15)
    at TCP._handle.close (net.js:606:12)
```

**Comment by AljoschaMeyer** [comment]
And in case it is relevant:

`npm ls -g git-ssb`:

```
/home/aljoscha/.node_modules/lib
└── git-ssb@2.3.6
```

Since this error seems to come from git-ssb, is there a way to use patchwork without it starting up git-ssb internally?

**Comment by AljoschaMeyer** [comment]
> Just to clarify, it sounds like you're reproducing this on two environments (please correct me if I'm wrong)

Yup, that's right.

`npm update -g git-ssb` installs version `2.3.6`, newer versions are on `ssb-npm`, which i have not set up yet.

> As a workaround you might be able to replace this with if (false)

Yay, that works. I still have no idea how it managed to randomly break though.

**Comment by doublec** [comment]
I am also getting this exact error, running Patchwork from Git and running the Patchwork-3.11.4 App Image. It started occurring after updating to Ubuntu 18.10 for me.

**Comment by christianbundy** [comment]
@doublec The error itself should be harmless as long as Patchwork continues working. If Patchwork isn't working, could you open a new issue?
