### ISSUE TITLE
Error: Contact state requires an id

### ISSUE THREAD

**Issue by qypea** [ssbc/patchwork#890]
When trying to build and run v3.11.4 from source the electron window keeps spinning forever, never fills out with data. On the console I get the following message.

Host machine is Fedora 28, amd64

```
Error: Contact state requires an id!
    at get (/opt/ssbc/patchwork/node_modules/patchcore/contact/obs.js:122:32)
    at update (/opt/ssbc/patchwork/node_modules/patchcore/contact/obs.js:105:17)
    at pull.drain.item (/opt/ssbc/patchwork/node_modules/patchcore/contact/obs.js:87:13)
    at /opt/ssbc/patchwork/node_modules/pull-stream/sinks/drain.js:24:37
    at PacketStreamSubstream.weird.read (/opt/ssbc/patchwork/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/opt/ssbc/patchwork/node_modules/packet-stream/index.js:204:12)
    at PacketStream.write (/opt/ssbc/patchwork/node_modules/packet-stream/index.js:135:41)
    at /opt/ssbc/patchwork/node_modules/muxrpc/pull-weird.js:56:15
    at /opt/ssbc/patchwork/node_modules/pull-stream/sinks/drain.js:24:37
    at /opt/ssbc/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
```
![patchwork-loading](https://user-images.githubusercontent.com/1694406/48485217-203d4b80-e7cd-11e8-9412-17b7a01250be.jpg)

**Comment by mmckegg** [comment]
Hmmm, not sure what this was. But since 3.12.0 is about to be released, I'm going to close this. If something like this comes up in the new release, please re-open!
