### ISSUE TITLE
Challenge not accepted while trying to connect to pubs

### ISSUE THREAD

**Issue by patrickbolle** [ssbc/patchwork#929]
Running Patchwork 3.11.4 from AppImage on Debian Stretch.

Running Patchwork via command-line with the extra debugging/logging command shows this:

```
➜  Downloads ./Patchwork-3.11.4-linux-x86_64\(1\).AppImage --logging.level info
installed: X-AppImage-BuildId=c5ceb290-e2f6-11a8-07c2-b1ba5ffda287 image: X-AppImage-Bu
{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3 },
  connections: { incoming: { net: [Array] }, outgoing: { net: [Array] } },
  path: '/home/patrick/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: [ 'info' ] }
ssb-friends: createFriendStream legacy api used
git-ssb is not installed, or not available in path
SHS:CONNECT shs:JUBGIPQ3KzZEqc03FX53bZucL9i/UqgHQgpPyJHPzpw=
ssb-friends: stream legacy api used
ssb-friends: get legacy api used
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
{ message: 'challenge not accepted',
  name: 'Error',
  stack: 'Error: challenge not accepted\n    at abort (/tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/secret-handshake/protocol.js:36:45)\n    at Object.cb (/tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/secret-handshake/protocol.js:42:24)\n    at drain (/tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/pull-reader/index.js:42:23)\n    at /tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/pull-reader/index.js:59:18\n    at /tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/pull-reader/index.js:20:7\n    at drain (/tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/stream-to-pull-stream/index.js:141:18)\n    at Socket.<anonymous> (/tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/stream-to-pull-stream/index.js:162:5)\n    at emitOne (events.js:121:20)\n    at Socket.emit (events.js:211:7)\n    at TCP._handle.close [as _onclose] (net.js:554:12)' }
```

I've tried connecting to all 3 of the current 'public' pubs on the pub list here (https://github.com/ssbc/ssb-server/wiki/Pub-Servers). For reference:

>   zie.one, run by zie (@FcZCT4lCttqOUhIAyxi00ix2gjYJJ2E2FFekwN4/860=.ed25519)
>   ssb.organicdesign.pub, run by Aran (@WeZBYERzjvfOVlgU7vMz7RSheqe4WaGEd87ewbMvnvQ=.ed25519)
>    qypea1.dyndns.info, run by DavidW (@PZjQKGbh9KrWHAp1lo9nH/WXqGLp5rpqpVYLccJLkE4=.ed25519) qypea1.dyndns.info:8008:@6lOh+rLq4MQubPQoKenbB9ipq75NVc2FAjy30MTc08o=.ed25519~93RP4aT6YNm+7++Ab3VQd+w/CL2w6p8QuX7fRaUs9cY=

Maybe related/unrelated:

Over the past week or so I've been having an issue with Patchwork not loading/grabbing any new posts (when it does it is extremely sporadic, maybe once every 2 days of it being open). First referenced in thread: %C2FsGWK+IGxR23IZIC0+7Msf7iTf9HN/tlzFWVSOqtU=.sha256

Any ideas here?

Thanks!

**Comment by christianbundy** [comment]
Hey @patrickbolle, sorry you've been running into these problems.

I think "challenge not accepted" is normal for pubs you've already redeemed an invite with (ssb.organicdesign.pub), and I'm unsure about the others. Could you run `ls -la ~/.ssb/gossip*`? I want to make sure that you only have one file that shows up. For example, I see:

```console
$ ls -la ~/.ssb/gossip*
-rw-r--r-- 1 christianbundy christianbundy 321983 Jan 28 11:35 /home/christianbundy/.ssb/gossip.json
```

This is one of those difficult-to-debug problems because the public pubs aren't administered by Patchwork -- sometimes they have downtime and/or bugs and there's no way to troubleshoot/debug unless it's *your* pub.

**Comment by patrickbolle** [comment]
Hi Christian, thanks for the quick reply. Running that command gives me
the following:
-rw-r--r-- 1 patrick patrick 335572 Jan 28 14:41
/home/patrick/.ssb/gossip.json
I can give it a wait for a few days regarding the pubs, it's just weird
as all week I'd been having issues as wlel.
Thanks!

**Comment by patrickbolle** [comment]
Quick update today.

Trying to join zie.one pub now gives me the error message:

`An error occurred while attempting to redeem invite - could not connect to sbot`

Not sure if this is related (or maybe it's a pub error and not on my side at all) but thought I would add this in anyways.

**Comment by patrickbolle** [comment]
Update:

Today installed Patchwork from source. On initial load it loaded more data than when I opened Patchwork last (release AppImage), but I still encounter the pub joining error.

Here are more logs:
```
➜  patchwork git:(master) ✗ npm start

> ssb-patchwork@3.12.0-dev start /home/patrick/Projects/patchwork
> electron index.js

{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3, autoPopulate: false },
  connections: 
   { outgoing: { net: [Array] },
     incoming: { net: [Array], ws: [Array], unix: [Array] } },
  path: '/home/patrick/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: [],
  keys: 
   { curve: 'ed25519',
     public: 'JUBGIPQ3KzZEqc03FX53bZucL9i/UqgHQgpPyJHPzpw=.ed25519',
     private: null,
     id: '@JUBGIPQ3KzZEqc03FX53bZucL9i/UqgHQgpPyJHPzpw=.ed25519' },
  remote: 'unix:/home/patrick/.ssb/socket:~noauth:JUBGIPQ3KzZEqc03FX53bZucL9i/UqgHQgpPyJHPzpw=' }
Init replication limiter. maxNumConnections: 10, modeChangeThreshold: 100
Replication obs called, Limited mode enabled:  false
git-ssb is not installed, or not available in path
Listening on undefined:8008 (multiserver net plugin)
listening on socket unix:/home/patrick/.ssb/socket
unix socket client
{ message: 'stream ended with:0 but wanted:64',
  name: 'Error',
  stack: 'Error: stream ended with:0 but wanted:64\n    at drain (/home/patrick/Projects/patchwork/node_modules/pull-reader/index.js:43:26)\n    at /home/patrick/Projects/patchwork/node_modules/pull-reader/index.js:63:18\n    at /home/patrick/Projects/patchwork/node_modules/pull-reader/index.js:20:7\n    at drain (/home/patrick/Projects/patchwork/node_modules/stream-to-pull-stream/index.js:141:18)\n    at Socket.<anonymous> (/home/patrick/Projects/patchwork/node_modules/stream-to-pull-stream/index.js:162:5)\n    at emitOne (events.js:121:20)\n    at Socket.emit (events.js:211:7)\n    at TCP._handle.close [as _onclose] (net.js:554:12)' }
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
{ message: 'stream ended with:0 but wanted:64',
  name: 'Error',
  stack: 'Error: stream ended with:0 but wanted:64\n    at drain (/home/patrick/Projects/patchwork/node_modules/pull-reader/index.js:43:26)\n    at /home/patrick/Projects/patchwork/node_modules/pull-reader/index.js:63:18\n    at /home/patrick/Projects/patchwork/node_modules/pull-reader/index.js:20:7\n    at drain (/home/patrick/Projects/patchwork/node_modules/stream-to-pull-stream/index.js:141:18)\n    at Socket.<anonymous> (/home/patrick/Projects/patchwork/node_modules/stream-to-pull-stream/index.js:162:5)\n    at emitOne (events.js:121:20)\n    at Socket.emit (events.js:211:7)\n    at TCP._handle.close [as _onclose] (net.js:554:12)' }
{ key: '%O4i0vFQwMQvJTdYZRiwGdlTjEZfXp0ChWcKK/LC4bbg=.sha256',
  value: 
   { previous: '%QX/o6W0R3A17tuP4IlyeicicBFcub6l8pCJjRk7UI1M=.sha256',
     author: '@JUBGIPQ3KzZEqc03FX53bZucL9i/UqgHQgpPyJHPzpw=.ed25519',
     sequence: 173,
     timestamp: 1550079882300,
     hash: 'sha256',
     content: { type: 'pub', address: [Object] },
     signature: 'KO/D+yXGpXIigb8XmpKy6VkAZvh7ySGNsaxbY9LvwiOAyorkTSNiolr5oGcPJqJlZXq1JRFiVPxJrI8R6COiCg==.sig.ed25519' },
  timestamp: 1550079882302 }
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
{ message: 'stream ended with:0 but wanted:64',
  name: 'Error',
  stack: 'Error: stream ended with:0 but wanted:64\n    at drain (/home/patrick/Projects/patchwork/node_modules/pull-reader/index.js:43:26)\n    at /home/patrick/Projects/patchwork/node_modules/pull-reader/index.js:63:18\n    at /home/patrick/Projects/patchwork/node_modules/pull-reader/index.js:20:7\n    at drain (/home/patrick/Projects/patchwork/node_modules/stream-to-pull-stream/index.js:141:18)\n    at Socket.<anonymous> (/home/patrick/Projects/patchwork/node_modules/stream-to-pull-stream/index.js:162:5)\n    at emitOne (events.js:121:20)\n    at Socket.emit (events.js:211:7)\n    at TCP._handle.close [as _onclose] (net.js:554:12)' }
{ message: 'stream ended with:0 but wanted:64',
  name: 'Error',
  stack: 'Error: stream ended with:0 but wanted:64\n    at drain (/home/patrick/Projects/patchwork/node_modules/pull-reader/index.js:43:26)\n    at /home/patrick/Projects/patchwork/node_modules/pull-reader/index.js:63:18\n    at /home/patrick/Projects/patchwork/node_modules/pull-reader/index.js:20:7\n    at drain (/home/patrick/Projects/patchwork/node_modules/stream-to-pull-stream/index.js:141:18)\n    at Socket.<anonymous> (/home/patrick/Projects/patchwork/node_modules/stream-to-pull-stream/index.js:162:5
```

This happened after trying to join the 3 current 'open' public pubs from here - https://github.com/ssbc/ssb-server/wiki/Pub-Servers

**Comment by christianbundy** [comment]
Hmm. I'm not really sure how to help debug this, since those pub servers are run by other people.

Brainstorming things that might help:

- disable your firewall
- try from a different location (router firewall?)
- set up a pub locally to test (requires another computer or rpi or something)

Sorry I can't be of more help, some of this stuff is very opaque to debug.

**Comment by Powersource** [comment]
Shouldn't stalebot have kicked in by now?

Beep boop

**Comment by christianbundy** [comment]
It doesn't touch issues with an assignee, which gives us a way to pin issues *s u b j e c t i v e l y*. Thanks for closing this though, I didn't realize I was still keeping it open.

**Comment by Powersource** [comment]
Aah ok. I guess that also answers my question why you are assigned to so many issues :P

**Comment by christianbundy** [comment]
Haha, yep! If there's anything super old where it's obviously good to close please feel free though, the assignee thing is just an experiment with subjective roadmaps so it's a bit rough around the edges. 🙃
