### ISSUE TITLE
Forked feed: published posts have incorrect sequence ID

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#967]
Weird things I've been doing:

- working on flumedb deletion
- using Patchwork `master`
- using the Patchwork 3.11.5 AppImage
- using my Patchwork pull requests (https://github.com/ssbc/patchwork/pull/959 and https://github.com/ssbc/patchwork/pull/961)
- deleted `~/.ssb/flume/last.json` (https://github.com/ssbc/patchwork/issues/957#issuecomment-474023819)

Anyway, I think my feed is forked. It looks like my last message came through six days ago (`
%5bx3E5HOVZxFUxuhjKMFsby2N263oZNQlKFwduW0CME=.sha256`) so if anyone has a different latest messages from me that would be good to know. I'm going to start debugging now.

---

This is probably my fault, I just wanted to make a public post about it in case others have a different latest message from me.

**Comment by christianbundy** [comment]
How could I forget? An example message:

```json
{
  "previous": "%B6z7VU0yqNfKg6ghjRm/SuLTKyHsHPta2rl4E2Xvwoc=.sha256",
  "sequence": 323,
  "author": "@+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519",
  "timestamp": 1553007634907,
  "hash": "sha256",
  "content": "9iiKLembgYk5ZIr1OHMhuGBPP2ZQQNhGoE7wn/FbvbcqfMTcF0WdgNVqj3ma+3CZzxerYIRooh0+9X/B76JCGCAwJf6AIkZr38R7ALbshkbO3rpMldQvF3ta5AMs8YhpuNWJrOPRj1ZVbjT0P7zAL7g0uULKEATw4q8BGStKsibRJWLgh+1rWq6zGYnzfEhkAbb0inW1+pwoxKxolzh4oQjAu03C+m+lY53FPDeGCZSrgmQ5Yy9anANbw7/JxtWnl0HBTyP6nRE38MiZSq7XecndFBPs6vjSMwRMyUMNlknRHVH0HLT/ExO8XSbcNbfVLa+r6/B7HAkl6aQHGQc3ntrc5lJKFBFlieT2oX8tBXyI5shJUhtCIM9qhG6RyAnoAGkRwpVRy4lT2oqWgKnK+ZZd7Ym2dnANjQUIww9oH2wyJtZM+9mFoc+wGzg+akr2uWyjEMtzIG9aAQWV141rKraiY+GutoGbUkb5uv5AL41OUVSErxGBW9+4bJlJVsJoWdaqnQaYVQ7kDcRsCn7YddJla7MkZillqtjrINvRWpaT4DGxUW9zH1Q5b2cIKmzF2+QJJpKnFOlq5ItmIv+EKKKFYk5S478GJa0ylMh1OwK9zTJybdYBZymYrqPM14GVOTQEbVzfQyVd/SrvIGLYDDF2MHmohEPAvbJsB2sOI/YzZKHNK7I/Kl2VBcooRtA6tL4+ciQnB6yRP43h7zPmJtUk+iZzjQxr/EEi0fruiocr9RMi4BZsAIuLUWWPgZr5813+HHesNBvZic3SNH16jgdY7G9iAdMFBQACZ8gb8CT68GnHJyYWXPMYf350wz2Y7JhppIXrRiECAnwdsYOyHsWxJEOBqeW4Gl6pP9rLewuxY4f+LcdA1CN2rVz6etpr4/H5KMnwDVhlU4dcfkgGmB4PpVPOGGt+i5GkoGaZ92KJcQbM0MWna87CCoV6qulphohBba8dFLhjaJrVN50eeElIruQjRmyqu9F3glYlMMYKZT72dH+olEIDjpgTT/W4OW8e+MICNfc9d+gHI/9gsHzEpSZEHbz0lpConWN+PjAePBMnByoebOWcteH/Y5oe6eC1d+/jDhziHBoBKZ/LdQSXOz04GtL03P4gKFDjYRqEu2MM5QJoCoBoDN53fTod9gYiJGyvU7hoz9WpHYgEPQ1khmWmbp7CEENNH/HyRmwmRLeXOPUiUQGzOiBsqikYJv81v50eOQRMdCX2QajonDOQqYllLt7rXspXHdwjjYwaYZq6PoLd8yVA1FPfNYSTx6ZbnnjzDuPWEh4/zWzX42/7oh8I4I7d0rcxXwFCS4qN4gvrFqRov/meloGRs0Sh2DP4H1x5IlgxsDix9l6QcVzx028qb1IcRYRGWlr85Iil48KXPR2/qJ3C8hjLt1xRnT7zlIucGTTSEOKkab0kSBHUbkm3c8Jo1sUPDF4tsX1PBDih+wW+7/Gd25WLJy+BUh8kKaMcJrp+xYqPA/4U9l7wjxy7yX8C+Af+LtTckEHmiDH+/k6h3dfniWyD82qgde84R2NDevfG6szBKkiu/sZqulAi6AxLwiHDOwxtmWpWXiMcIBZYArQMBPGI/iYvZ2mNZmbHJGYiGiwz1LKOgCWfb58ZBzxOI7WgCismnHOZHUmw8JYCCGMz5Pqe1zq42tYzyAJsIGV6UY6pwO645xsnXDFETphDoiw6Y222kKJESxauMasfdnROJt+BbMSQZBQjfttGV+Z++r/QbzcKXRpEH9ichO7DfGo52czbtzteMu3fzWyM3PlE+sow3iqDQZkjUNRTN9UgAbkXa/nr5XcD+SB3jqzkH45MQvmiCjXbk+jT0kQ0GINW8ygg2mXLkUCMqMt7RMgTkdXA2obCjYXl/liIsBXb2RJ+5douEOjPOBFWi6iUPlvz0EfZo7JfW6MT78xP6swqOtFkNYVMYg363TfrUmRFbrFo18Mift302eWaS8+mvbZ5jJ5xZu5PM5/bwiTRyA5e0WOfCMBNwprgHz7j1OwfQTjLtQiEgBgh14rEsIwNLM6Z7A4Kr4awx4pEJK2u2KLsLirGFFOkZbyjgs8VTDOsv6s7RncElUKQ.box",
  "signature": "redacted"
}
```

**Comment by christianbundy** [comment]
I think we're good. I forked my feed with my same-as implementation. :upside_down_face: 

`%CRxZR8PmT+etS6c0osbfQPv1/ZcrbTKQzezeSR43sns=.sha256`

**Comment by christianbundy** [comment]
Error I'm seeing while reindexing:

```
TypeError: Cannot read property 'content' of undefined
    at bumpFilter (/home/christianbundy/src/ssbc/patchwork/sbot/private-feed.js:110:17)
    at threadSummary (/home/christianbundy/src/ssbc/patchwork/sbot/private-feed.js:99:27)
    at pull.drain (/home/christianbundy/src/ssbc/patchwork/lib/thread-summary.js:34:7)
    at /home/christianbundy/src/ssbc/patchwork/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/christianbundy/src/ssbc/patchwork/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/christianbundy/src/ssbc/patchwork/node_modules/pull-stream/throughs/filter.js:17:11
    at drain (/home/christianbundy/src/ssbc/patchwork/node_modules/pull-paramap/index.js:23:11)
    at /home/christianbundy/src/ssbc/patchwork/node_modules/pull-paramap/index.js:37:11
    at /home/christianbundy/src/ssbc/patchwork/node_modules/pull-stream/throughs/through.js:19:9
    at /home/christianbundy/src/ssbc/patchwork/node_modules/pull-stream/throughs/filter.js:17:11
```
