### ISSUE TITLE
 Cannot read property 'apply' or 'pendingUpdates' of undefined

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#973]
New bug(s) in `master` currently:

```
base.html:19 TypeError: Cannot read property 'apply' of undefined
    at ProtoComputed.update (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/computed.js:134:42)
    at ProtoComputed.listen (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/computed.js:91:17)
    at ProtoComputed.getValue (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/computed.js:196:12)
    at ProtoComputed.MutantComputed (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/computed.js:55:19)
    at resolve (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/lib/apply-properties.js:123:41)
    at applyProperties (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/lib/apply-properties.js:60:21)
    at Element (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/html-element.js:64:3)
    at module.exports (/home/christianbundy/src/ssbc/patchwork/node_modules/mutant/html-element.js:13:10)
    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/modules/contact/html/follow-toggle.js:65:13)
    at Object.followToggle (/home/christianbundy/src/ssbc/patchwork/node_modules/depject/apply.js:18:30)
console.error @ base.html:19
base.html:19 TypeError: Cannot read property 'pendingUpdates' of undefined
    at setTimeout (/home/christianbundy/src/ssbc/patchwork/modules/page/html/render/profile.js:60:20)```

**Comment by christianbundy** [comment]
I forgot that I'd edited that file. My fault, again...
